import type { Question } from '../types'

export const HISTORY_QUESTIONS: Question[] = [
  // ─── EASY ───────────────────────────────────────────────────────────────────
  {
    id: 'history_easy_001',
    subject: 'history',
    difficulty: 'easy',
    question: 'What ancient wonder was built in Egypt?',
    answers: ['The Colosseum', 'The Great Pyramid of Giza', 'The Great Wall', 'The Parthenon'],
    correctIndex: 1,
    explanation: 'The Great Pyramid of Giza was built around 2560 BC in Egypt. It is the only ancient wonder of the world still standing today.',
    hint: 'It is shaped like a triangle and is in the desert.',
    tags: ['ancient civilizations', 'landmarks'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'history_easy_002',
    subject: 'history',
    difficulty: 'easy',
    question: 'Who was the first person to walk on the Moon?',
    answers: ['Buzz Aldrin', 'Yuri Gagarin', 'Neil Armstrong', 'John Glenn'],
    correctIndex: 2,
    explanation: 'Neil Armstrong was the first human to walk on the Moon on July 20, 1969, during the Apollo 11 mission. He said: "That\'s one small step for man, one giant leap for mankind."',
    tags: ['historical figures', 'exploration'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'history_easy_003',
    subject: 'history',
    difficulty: 'easy',
    question: 'Which country built the Great Wall?',
    answers: ['Japan', 'China', 'India', 'Mongolia'],
    correctIndex: 1,
    explanation: 'China built the Great Wall over many centuries, mostly to protect against invasions from the north. Construction started around 7th century BC.',
    tags: ['landmarks', 'ancient civilizations'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'history_easy_004',
    subject: 'history',
    difficulty: 'easy',
    question: 'In what city is the Eiffel Tower located?',
    answers: ['London', 'Rome', 'Paris', 'Berlin'],
    correctIndex: 2,
    explanation: 'The Eiffel Tower is in Paris, France. It was built in 1889 by Gustave Eiffel for the World\'s Fair and was the world\'s tallest man-made structure at the time.',
    tags: ['landmarks'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'history_easy_005',
    subject: 'history',
    difficulty: 'easy',
    question: 'Which ancient civilization built the Colosseum?',
    answers: ['Greek', 'Egyptian', 'Roman', 'Persian'],
    correctIndex: 2,
    explanation: 'The Romans built the Colosseum in Rome, Italy. It was completed around 80 AD and could hold up to 80,000 spectators watching gladiator fights.',
    tags: ['ancient civilizations', 'landmarks'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'history_easy_006',
    subject: 'history',
    difficulty: 'easy',
    question: 'What was the ancient Egyptian writing system called?',
    answers: ['Cuneiform', 'Hieroglyphics', 'Sanskrit', 'Latin'],
    correctIndex: 1,
    explanation: 'Ancient Egyptians used hieroglyphics — a system of picture symbols representing sounds and ideas. They were deciphered in 1822 using the Rosetta Stone.',
    tags: ['ancient civilizations', 'writing'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'history_easy_007',
    subject: 'history',
    difficulty: 'easy',
    question: 'Before using paper money, what did people trade before coins and cash existed?',
    answers: ['Plastic cards', 'Bartering (trading goods)', 'Digital tokens', 'Bank notes'],
    correctIndex: 1,
    explanation: 'Before money was invented, people used bartering — trading goods directly. For example, a farmer might trade wheat for a blacksmith\'s tools.',
    tags: ['timeline concepts', 'economy'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'history_easy_008',
    subject: 'history',
    difficulty: 'easy',
    question: 'Which explorer is credited with completing the first voyage around the world?',
    answers: ['Christopher Columbus', 'Vasco da Gama', 'Ferdinand Magellan', 'James Cook'],
    correctIndex: 2,
    explanation: 'Ferdinand Magellan led the first expedition to sail around the world (1519–1522). Though he died before completing it, his crew finished the journey.',
    tags: ['explorers', 'historical figures'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'history_easy_009',
    subject: 'history',
    difficulty: 'easy',
    question: 'What was the name of the long ocean-spanning trade route connecting Asia and Europe?',
    answers: ['The Silk Road', 'The Spice Trail', 'The Golden Highway', 'The Eastern Path'],
    correctIndex: 0,
    explanation: 'The Silk Road was a network of trade routes connecting China to the Mediterranean for over 1,500 years, carrying silk, spices, and ideas.',
    tags: ['trade', 'ancient civilizations'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'history_easy_010',
    subject: 'history',
    difficulty: 'easy',
    question: 'On which continent did ancient Egyptian civilization develop?',
    answers: ['Asia', 'Europe', 'Africa', 'South America'],
    correctIndex: 2,
    explanation: 'Ancient Egypt developed along the Nile River in Africa. The Nile\'s annual floods deposited rich soil, making farming possible in the desert.',
    tags: ['ancient civilizations', 'geography'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'history_easy_011',
    subject: 'history',
    difficulty: 'easy',
    question: 'What invention allowed books to be printed quickly and cheaply in the 15th century?',
    answers: ['The typewriter', 'The printing press', 'Ink cartridges', 'The photocopier'],
    correctIndex: 1,
    explanation: 'Johannes Gutenberg invented the printing press around 1440. It allowed books to be produced much faster, spreading ideas and literacy across Europe.',
    tags: ['inventions', 'historical figures'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'history_easy_012',
    subject: 'history',
    difficulty: 'easy',
    question: 'Which famous female leader was the last Pharaoh of Ancient Egypt?',
    answers: ['Nefertiti', 'Cleopatra', 'Hatshepsut', 'Isis'],
    correctIndex: 1,
    explanation: 'Cleopatra VII (69–30 BC) was the last active ruler of the Ptolemaic Kingdom of Egypt. She was known for her intelligence and formed alliances with Julius Caesar and Mark Antony.',
    tags: ['historical figures', 'ancient civilizations'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'history_easy_013',
    subject: 'history',
    difficulty: 'easy',
    question: 'What ancient Greek building in Athens was dedicated to the goddess Athena?',
    answers: ['The Colosseum', 'The Parthenon', 'The Acropolis of Athens', 'The Temple of Zeus'],
    correctIndex: 1,
    explanation: 'The Parthenon, built around 447–432 BC on the Acropolis hill in Athens, was a temple dedicated to the goddess Athena, patron of the city.',
    tags: ['ancient civilizations', 'landmarks'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'history_easy_014',
    subject: 'history',
    difficulty: 'easy',
    question: 'What does BC stand for in historical dates?',
    answers: ['Before Creation', 'Before Calendar', 'Before Christ', 'Basic Century'],
    correctIndex: 2,
    explanation: 'BC stands for "Before Christ" and counts years backward from the birth of Jesus. The higher the BC number, the further back in time. (BCE — Before Common Era — means the same thing.)',
    tags: ['timeline concepts'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'history_easy_015',
    subject: 'history',
    difficulty: 'easy',
    question: 'Which ancient civilization is famous for building the Machu Picchu citadel?',
    answers: ['Aztec', 'Mayan', 'Inca', 'Olmec'],
    correctIndex: 2,
    explanation: 'Machu Picchu was built by the Inca civilization in Peru around 1450 AD. It sits high in the Andes Mountains and was never discovered by Spanish conquistadors.',
    tags: ['ancient civilizations', 'landmarks'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'history_easy_016',
    subject: 'history',
    difficulty: 'easy',
    question: 'What was the name of the ship that brought the Pilgrims to America in 1620?',
    answers: ['The Endeavour', 'The Mayflower', 'The Santa Maria', 'The Beagle'],
    correctIndex: 1,
    explanation: 'The Mayflower carried 102 passengers from England to Plymouth, Massachusetts in 1620. The passengers became known as the Pilgrims.',
    tags: ['historical figures', 'exploration'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'history_easy_017',
    subject: 'history',
    difficulty: 'easy',
    question: 'In which century did Christopher Columbus sail to the Americas?',
    answers: ['13th century (1200s)', '14th century (1300s)', '15th century (1400s)', '16th century (1500s)'],
    correctIndex: 2,
    explanation: 'Columbus sailed in 1492, which is in the 15th century (the 1400s). A century is 100 years, and the 15th century covers 1401–1500.',
    tags: ['timeline concepts', 'explorers'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'history_easy_018',
    subject: 'history',
    difficulty: 'easy',
    question: 'Who was famous for saying "I have a dream" in 1963?',
    answers: ['Nelson Mandela', 'Mahatma Gandhi', 'Martin Luther King Jr.', 'Frederick Douglass'],
    correctIndex: 2,
    explanation: 'Martin Luther King Jr. delivered his famous "I Have a Dream" speech on August 28, 1963, calling for an end to racism and equality for all Americans.',
    tags: ['historical figures'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'history_easy_019',
    subject: 'history',
    difficulty: 'easy',
    question: 'What were the ancient Romans famous for building across their empire?',
    answers: ['Ziggurats', 'Roads and aqueducts', 'Pagodas', 'Igloos'],
    correctIndex: 1,
    explanation: 'Romans built an extensive network of straight roads for their armies and aqueducts (water channels) to supply cities with fresh water. Many are still visible today.',
    tags: ['ancient civilizations', 'engineering'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'history_easy_020',
    subject: 'history',
    difficulty: 'easy',
    question: 'In which modern-day country was the ancient civilization of Mesopotamia located?',
    answers: ['Egypt', 'Iran', 'Iraq', 'Turkey'],
    correctIndex: 2,
    explanation: 'Mesopotamia ("land between the rivers") was located between the Tigris and Euphrates rivers, in modern-day Iraq. It is often called the "Cradle of Civilization."',
    tags: ['ancient civilizations', 'geography'],
    xpReward: 10,
    timeLimit: 30,
  },

  // ─── MEDIUM ─────────────────────────────────────────────────────────────────
  {
    id: 'history_medium_001',
    subject: 'history',
    difficulty: 'medium',
    question: 'What event in 1789 marked the beginning of the French Revolution?',
    answers: ['The execution of King Louis XVI', 'The storming of the Bastille', 'The signing of the Magna Carta', 'The Battle of Waterloo'],
    correctIndex: 1,
    explanation: 'On July 14, 1789, Parisian citizens stormed the Bastille prison — a symbol of royal tyranny. This became a turning point that sparked the French Revolution.',
    tags: ['major events', 'revolutions'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'history_medium_002',
    subject: 'history',
    difficulty: 'medium',
    question: 'Which empire was ruled by Genghis Khan?',
    answers: ['Ottoman Empire', 'Roman Empire', 'Mongol Empire', 'British Empire'],
    correctIndex: 2,
    explanation: 'Genghis Khan founded the Mongol Empire in 1206. It became the largest contiguous land empire in history, stretching from China to Eastern Europe.',
    tags: ['world empires', 'historical figures'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'history_medium_003',
    subject: 'history',
    difficulty: 'medium',
    question: 'What invention by Alexander Graham Bell in 1876 changed communication forever?',
    answers: ['The telegraph', 'The telephone', 'The radio', 'The television'],
    correctIndex: 1,
    explanation: 'Alexander Graham Bell invented and patented the telephone in 1876. It allowed people to transmit speech electronically over distances for the first time.',
    tags: ['inventions', 'historical figures'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'history_medium_004',
    subject: 'history',
    difficulty: 'medium',
    question: 'Which two cities were famously destroyed by Mount Vesuvius in 79 AD?',
    answers: ['Rome and Naples', 'Pompeii and Herculaneum', 'Athens and Sparta', 'Carthage and Syracuse'],
    correctIndex: 1,
    explanation: 'Mount Vesuvius erupted in 79 AD, burying Pompeii and Herculaneum under ash and pumice. The preserved ruins were rediscovered in the 18th century.',
    tags: ['major events', 'ancient civilizations'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'history_medium_005',
    subject: 'history',
    difficulty: 'medium',
    question: 'What year did World War I begin?',
    answers: ['1910', '1914', '1918', '1939'],
    correctIndex: 1,
    explanation: 'World War I began in 1914 and ended in 1918. It was triggered by the assassination of Archduke Franz Ferdinand of Austria in Sarajevo.',
    tags: ['major events', 'wars'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'history_medium_006',
    subject: 'history',
    difficulty: 'medium',
    question: 'Which explorer was the first European to reach India by sailing around Africa?',
    answers: ['Christopher Columbus', 'Ferdinand Magellan', 'Vasco da Gama', 'Bartolomeu Dias'],
    correctIndex: 2,
    explanation: 'Vasco da Gama (Portuguese explorer) reached India by sailing around the Cape of Good Hope in Africa in 1498, opening a sea trade route between Europe and Asia.',
    tags: ['explorers', 'trade'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'history_medium_007',
    subject: 'history',
    difficulty: 'medium',
    question: 'What is the name of the document signed in 1215 that limited the power of the English king?',
    answers: ['The Bill of Rights', 'The Magna Carta', 'The Declaration of Independence', 'The Constitution'],
    correctIndex: 1,
    explanation: 'The Magna Carta (Great Charter) was signed in 1215. It was one of the first documents to establish that even the king must follow the law.',
    tags: ['major events', 'law'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'history_medium_008',
    subject: 'history',
    difficulty: 'medium',
    question: 'What empire was based in Constantinople (modern Istanbul, Turkey)?',
    answers: ['Roman Empire', 'Persian Empire', 'Byzantine Empire', 'Ottoman Empire'],
    correctIndex: 2,
    explanation: 'The Byzantine Empire was the eastern continuation of the Roman Empire, centered on Constantinople. It lasted from 330 AD until 1453 when it was conquered by the Ottoman Turks.',
    tags: ['world empires'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'history_medium_009',
    subject: 'history',
    difficulty: 'medium',
    question: 'Who wrote the theory of evolution by natural selection?',
    answers: ['Isaac Newton', 'Albert Einstein', 'Charles Darwin', 'Gregor Mendel'],
    correctIndex: 2,
    explanation: 'Charles Darwin published "On the Origin of Species" in 1859, proposing that species evolve over time through natural selection — where organisms best suited to their environment survive.',
    tags: ['historical figures', 'inventions'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'history_medium_010',
    subject: 'history',
    difficulty: 'medium',
    question: 'The ancient city of Carthage was located on which continent?',
    answers: ['Asia', 'Europe', 'Africa', 'South America'],
    correctIndex: 2,
    explanation: 'Carthage was a powerful ancient city located in what is now Tunisia, North Africa. It was a rival to Rome before being destroyed in 146 BC.',
    tags: ['ancient civilizations', 'geography'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'history_medium_011',
    subject: 'history',
    difficulty: 'medium',
    question: 'Which ancient trade route connected China to the Middle East and Europe?',
    answers: ['The Spice Route', 'The Silk Road', 'The Amber Road', 'The Maritime Route'],
    correctIndex: 1,
    explanation: 'The Silk Road was a network of trade routes stretching 6,400 km, active from about 130 BC to 1450 AD. It carried silk, spices, gems, and helped spread religions and ideas.',
    tags: ['trade', 'ancient civilizations'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'history_medium_012',
    subject: 'history',
    difficulty: 'medium',
    question: 'What was the name of the empire built by Alexander the Great at its largest?',
    answers: ['Persian Empire', 'Macedonian Empire', 'Greek Empire', 'Hellenistic Empire'],
    correctIndex: 1,
    explanation: 'Alexander the Great built the Macedonian (or Alexandrian) Empire. By 323 BC it stretched from Greece to northwestern India — one of the largest empires in history.',
    tags: ['world empires', 'historical figures'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'history_medium_013',
    subject: 'history',
    difficulty: 'medium',
    question: 'What major event began on October 19, 1929, affecting economies worldwide?',
    answers: ['World War II', 'The Great Depression (Black Tuesday)', 'The Russian Revolution', 'The oil crisis'],
    correctIndex: 1,
    explanation: 'The Great Depression began with the Wall Street Crash (Black Tuesday) on October 29, 1929. Stock markets collapsed worldwide, causing massive unemployment and poverty.',
    tags: ['major events', 'economy'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'history_medium_014',
    subject: 'history',
    difficulty: 'medium',
    question: 'Which country was NOT a member of the Allied Powers in World War II?',
    answers: ['United Kingdom', 'United States', 'Germany', 'Soviet Union'],
    correctIndex: 2,
    explanation: 'Germany was an Axis Power in World War II (along with Japan and Italy), fighting against the Allied Powers (UK, USA, USSR, France, and others).',
    tags: ['wars', 'major events'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'history_medium_015',
    subject: 'history',
    difficulty: 'medium',
    question: 'In which year did the Berlin Wall fall?',
    answers: ['1979', '1985', '1989', '1991'],
    correctIndex: 2,
    explanation: 'The Berlin Wall fell on November 9, 1989. It had divided East and West Berlin since 1961. Its fall symbolized the end of the Cold War and led to German reunification.',
    tags: ['major events'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'history_medium_016',
    subject: 'history',
    difficulty: 'medium',
    question: 'What was the name of Nelson Mandela\'s organization that fought against apartheid in South Africa?',
    answers: ['Freedom Front', 'African National Congress (ANC)', 'Pan African Alliance', 'South African Liberation Front'],
    correctIndex: 1,
    explanation: 'Nelson Mandela was a leader of the African National Congress (ANC), which fought against apartheid (a system of racial segregation). Mandela was imprisoned for 27 years before becoming South Africa\'s first democratically elected president in 1994.',
    tags: ['historical figures', 'major events'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'history_medium_017',
    subject: 'history',
    difficulty: 'medium',
    question: 'What was the Industrial Revolution?',
    answers: ['A political revolution in France', 'A shift from farming to machine-based manufacturing', 'A war between industrial nations', 'The invention of electricity'],
    correctIndex: 1,
    explanation: 'The Industrial Revolution (late 1700s–1800s) was a shift from hand production to machines, factories, and steam power, beginning in Britain. It transformed economies and societies worldwide.',
    tags: ['major events', 'inventions'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'history_medium_018',
    subject: 'history',
    difficulty: 'medium',
    question: 'The ancient Olympic Games were first held in which country?',
    answers: ['Italy', 'Egypt', 'Greece', 'Turkey'],
    correctIndex: 2,
    explanation: 'The ancient Olympic Games began in Olympia, Greece around 776 BC. They were held every four years to honor the god Zeus and were open only to Greek men.',
    tags: ['ancient civilizations', 'culture'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'history_medium_019',
    subject: 'history',
    difficulty: 'medium',
    question: 'What was the name of the first artificial satellite launched into space?',
    answers: ['Apollo 1', 'Sputnik 1', 'Explorer 1', 'Vostok 1'],
    correctIndex: 1,
    explanation: 'Sputnik 1, launched by the Soviet Union on October 4, 1957, was the first artificial satellite. It marked the beginning of the Space Age and the "space race."',
    tags: ['major events', 'inventions'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'history_medium_020',
    subject: 'history',
    difficulty: 'medium',
    question: 'Which famous trade route connected sub-Saharan Africa to North Africa and the Mediterranean world?',
    answers: ['The Silk Road', 'The Trans-Saharan Trade Route', 'The Indian Ocean Trade Route', 'The Amber Road'],
    correctIndex: 1,
    explanation: 'The Trans-Saharan Trade Route crossed the Sahara Desert, carrying gold, salt, ivory, and enslaved people between West Africa and North Africa for centuries.',
    tags: ['trade', 'geography'],
    xpReward: 20,
    timeLimit: 25,
  },

  // ─── HARD ────────────────────────────────────────────────────────────────────
  {
    id: 'history_hard_001',
    subject: 'history',
    difficulty: 'hard',
    question: 'What economic system dominated medieval Europe, where peasants worked land owned by lords in exchange for protection?',
    answers: ['Capitalism', 'Feudalism', 'Mercantilism', 'Communism'],
    correctIndex: 1,
    explanation: 'Feudalism was the social and economic system of medieval Europe. Peasants (serfs) farmed the lord\'s land and paid rent in crops or labor in exchange for protection and housing.',
    tags: ['world empires', 'economy', 'analysis'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'history_hard_002',
    subject: 'history',
    difficulty: 'hard',
    question: 'The assassination of which Austro-Hungarian royal triggered the chain of alliances that led to World War I?',
    answers: ['Emperor Franz Joseph', 'Archduke Franz Ferdinand', 'Kaiser Wilhelm II', 'Tsar Nicholas II'],
    correctIndex: 1,
    explanation: 'Archduke Franz Ferdinand was assassinated in Sarajevo on June 28, 1914. Austria-Hungary blamed Serbia, triggering a web of alliances that pulled all major European powers into war.',
    tags: ['wars', 'cause and effect'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'history_hard_003',
    subject: 'history',
    difficulty: 'hard',
    question: 'What term describes the period of cultural and intellectual revival in Europe between the 14th and 17th centuries?',
    answers: ['The Enlightenment', 'The Reformation', 'The Renaissance', 'The Baroque Period'],
    correctIndex: 2,
    explanation: 'The Renaissance ("rebirth" in French) was a cultural movement that began in Italy. It revived interest in classical Greek and Roman art, science, and philosophy.',
    tags: ['cultural history', 'analysis'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'history_hard_004',
    subject: 'history',
    difficulty: 'hard',
    question: 'Which treaty ended World War I and is often blamed for the conditions that led to World War II?',
    answers: ['Treaty of Paris', 'Treaty of Versailles', 'Treaty of Vienna', 'Treaty of Utrecht'],
    correctIndex: 1,
    explanation: 'The Treaty of Versailles (1919) ended WWI and imposed harsh penalties on Germany — demanding reparations, territorial losses, and military restrictions. Many historians argue these conditions contributed to the rise of the Nazi party.',
    tags: ['wars', 'cause and effect'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'history_hard_005',
    subject: 'history',
    difficulty: 'hard',
    question: 'What was the primary cause of the decline of the Western Roman Empire?',
    answers: ['A volcanic eruption', 'A single military defeat', 'Multiple factors including invasions, economic trouble, and political instability', 'A plague that killed all Romans'],
    correctIndex: 2,
    explanation: 'Rome\'s fall had multiple causes: barbarian invasions, economic problems, overextension, political corruption, and the split into Eastern/Western empires. Historians still debate the primary cause.',
    tags: ['cause and effect', 'world empires', 'analysis'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'history_hard_006',
    subject: 'history',
    difficulty: 'hard',
    question: 'Which Mongol leader conquered the largest contiguous land empire in history?',
    answers: ['Kublai Khan', 'Timur', 'Genghis Khan', 'Attila the Hun'],
    correctIndex: 2,
    explanation: 'Genghis Khan united Mongol tribes and conquered an empire stretching from China to Eastern Europe by 1227. His empire was the largest ever connected by land.',
    tags: ['world empires', 'historical figures'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'history_hard_007',
    subject: 'history',
    difficulty: 'hard',
    question: 'What significant effect did the Black Death (1347–1351) have on medieval European society?',
    answers: ['It caused the Roman Empire to fall', 'It led to labor shortages and gave surviving peasants more bargaining power', 'It united Europe under one king', 'It had no lasting social effects'],
    correctIndex: 1,
    explanation: 'The Black Death killed 30–60% of Europe\'s population. The resulting labor shortage forced lords to pay higher wages and grant more rights to surviving peasants, helping break down the feudal system.',
    tags: ['cause and effect', 'analysis'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'history_hard_008',
    subject: 'history',
    difficulty: 'hard',
    question: 'What was the main reason European nations competed to colonize Africa in the late 19th century?',
    answers: ['To spread democracy', 'To access raw materials, markets, and strategic territory', 'To help African populations develop', 'To escape poor climate in Europe'],
    correctIndex: 1,
    explanation: 'The "Scramble for Africa" (1881–1914) was driven by European nations seeking raw materials for industry, new markets for goods, and strategic advantages. By 1914, 90% of Africa was under European control.',
    tags: ['cause and effect', 'geography', 'analysis'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'history_hard_009',
    subject: 'history',
    difficulty: 'hard',
    question: 'What was the Enlightenment\'s key principle that influenced modern democratic governments?',
    answers: ['The divine right of kings', 'Natural rights and the social contract', 'Religious authority over state matters', 'Military strength determines leadership'],
    correctIndex: 1,
    explanation: 'Enlightenment thinkers like John Locke and Jean-Jacques Rousseau argued people have natural rights (life, liberty, property) and governments exist by the "social contract" — consent of the governed.',
    tags: ['analysis', 'cause and effect', 'ideas'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'history_hard_010',
    subject: 'history',
    difficulty: 'hard',
    question: 'How did geography influence the development of ancient Greek city-states?',
    answers: ['Flat plains encouraged unified government', 'Mountainous terrain led to isolated, independent city-states', 'Rivers provided easy travel between cities', 'Desert conditions forced cooperation'],
    correctIndex: 1,
    explanation: 'Greece\'s rugged mountain ranges and peninsulas made travel difficult, leading to isolated settlements that developed independently as city-states (poleis) like Athens and Sparta, each with their own laws and culture.',
    tags: ['geography', 'ancient civilizations', 'analysis'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'history_hard_011',
    subject: 'history',
    difficulty: 'hard',
    question: 'The Cold War was primarily a conflict between the USA and USSR over which two competing ideologies?',
    answers: ['Monarchy vs. Democracy', 'Capitalism vs. Communism', 'Colonialism vs. Independence', 'Fascism vs. Liberalism'],
    correctIndex: 1,
    explanation: 'The Cold War (1947–1991) was a geopolitical tension between the capitalist Western bloc (led by the US) and the communist Eastern bloc (led by the USSR). It involved arms races, space races, and proxy wars.',
    tags: ['major events', 'analysis'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'history_hard_012',
    subject: 'history',
    difficulty: 'hard',
    question: 'Why was the Suez Canal, opened in 1869, strategically important?',
    answers: ['It connected the Atlantic and Pacific Oceans', 'It connected the Mediterranean Sea to the Red Sea, shortening the route to Asia', 'It allowed submarines to travel undetected', 'It provided fresh water to the Sahara'],
    correctIndex: 1,
    explanation: 'The Suez Canal connects the Mediterranean and Red Seas, eliminating the need to sail around Africa. It dramatically shortened the sea route between Europe and Asia.',
    tags: ['geography', 'inventions', 'analysis'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'history_hard_013',
    subject: 'history',
    difficulty: 'hard',
    question: 'What role did the printing press play in the Protestant Reformation?',
    answers: ['It had no effect on the Reformation', 'It allowed Martin Luther\'s ideas to spread rapidly across Europe', 'It was used to print Catholic Bibles only', 'It was invented after the Reformation ended'],
    correctIndex: 1,
    explanation: 'The printing press (c.1440) allowed Martin Luther\'s 95 Theses (1517) to be copied and distributed across Europe rapidly. Without it, his ideas might have been suppressed by the Catholic Church.',
    tags: ['cause and effect', 'inventions', 'analysis'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'history_hard_014',
    subject: 'history',
    difficulty: 'hard',
    question: 'What was the significance of the Battle of Thermopylae (480 BC)?',
    answers: ['Greeks conquered Persia', '300 Spartans held back a huge Persian army, allowing Greece time to prepare', 'The Roman Empire defeated the Greeks', 'It ended the Trojan War'],
    correctIndex: 1,
    explanation: 'At Thermopylae, 300 Spartans and allies held back the massive Persian army for three days. Though defeated, they slowed the Persian advance and inspired Greek resistance, which ultimately drove Persia out of Greece.',
    tags: ['ancient civilizations', 'wars', 'analysis'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'history_hard_015',
    subject: 'history',
    difficulty: 'hard',
    question: 'What was the Columbian Exchange?',
    answers: ['A peace treaty between Spain and the Americas', 'The transfer of plants, animals, and diseases between the Americas and Europe after 1492', 'Columbus\'s trade deal with indigenous peoples', 'A stock market founded by Columbus'],
    correctIndex: 1,
    explanation: 'The Columbian Exchange was the widespread transfer of plants (potatoes, tomatoes, maize), animals (horses, cattle), and diseases between the Americas and Afro-Eurasia following Columbus\'s 1492 voyage. It transformed global diets and had devastating effects on indigenous populations through disease.',
    tags: ['cause and effect', 'geography', 'explorers'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'history_hard_016',
    subject: 'history',
    difficulty: 'hard',
    question: 'Why did the ancient city of Rome transition from a Republic to an Empire?',
    answers: ['A foreign army conquered Rome and installed an emperor', 'Internal political conflict and civil wars led Julius Caesar and then Augustus to assume power', 'The Senate voted to create an emperor', 'A natural disaster destroyed the Republic\'s government buildings'],
    correctIndex: 1,
    explanation: 'The Roman Republic fell due to civil wars and political instability. Julius Caesar seized power (49 BC) and after his assassination, his heir Augustus became the first Roman Emperor (27 BC).',
    tags: ['world empires', 'cause and effect', 'analysis'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'history_hard_017',
    subject: 'history',
    difficulty: 'hard',
    question: 'What was the primary long-term effect of the Transatlantic Slave Trade on Africa?',
    answers: ['Africa became more economically powerful', 'Significant depopulation and destabilization of African societies', 'African nations gained independence faster', 'It created new trade partnerships that benefited Africa'],
    correctIndex: 1,
    explanation: 'The Transatlantic Slave Trade (15th–19th centuries) resulted in the forced removal of 12+ million Africans. This devastated populations, disrupted societies, and fueled wars between African kingdoms, leaving long-lasting social and economic damage.',
    tags: ['cause and effect', 'analysis'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'history_hard_018',
    subject: 'history',
    difficulty: 'hard',
    question: 'What was the Meiji Restoration in Japan (1868)?',
    answers: ['A military coup that replaced democracy with dictatorship', 'Japan\'s modernization program — adopting Western technology while preserving Japanese culture', 'Japan\'s conquest of neighboring countries', 'The restoration of a destroyed temple'],
    correctIndex: 1,
    explanation: 'The Meiji Restoration transformed Japan from a feudal society to a modern industrial nation. Japan adopted Western science, military techniques, and industry while maintaining Japanese identity, becoming a major world power by 1900.',
    tags: ['major events', 'analysis'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'history_hard_019',
    subject: 'history',
    difficulty: 'hard',
    question: 'How did the geography of the Nile River Valley contribute to the rise of ancient Egyptian civilization?',
    answers: ['The Nile provided barriers that prevented all foreign trade', 'Annual flooding deposited rich silt, enabling farming in the desert', 'The Nile\'s fish was the only food source', 'It prevented invasions from all sides'],
    correctIndex: 1,
    explanation: 'The Nile flooded annually, depositing nutrient-rich silt that made the surrounding land extremely fertile. This predictable abundance of food allowed Egyptians to develop specialized roles, complex society, and great monuments.',
    tags: ['geography', 'ancient civilizations', 'analysis'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'history_hard_020',
    subject: 'history',
    difficulty: 'hard',
    question: 'What was the main goal of the Non-Aligned Movement founded in 1961?',
    answers: ['To form a military alliance against NATO', 'To prevent newly independent nations from being pulled into the US-Soviet Cold War rivalry', 'To create a new world currency', 'To unite all African nations into one country'],
    correctIndex: 1,
    explanation: 'The Non-Aligned Movement, founded by leaders including Nehru (India), Nasser (Egypt), and Tito (Yugoslavia), allowed newly independent nations to avoid taking sides in the Cold War and assert their own political and economic interests.',
    tags: ['major events', 'analysis', 'geography'],
    xpReward: 35,
    timeLimit: 20,
  },
]
