import type { Question } from '../types'

export const LANGUAGE_QUESTIONS: Question[] = [
  // ─── EASY ───────────────────────────────────────────────────────────────────
  {
    id: 'language_easy_001',
    subject: 'language',
    difficulty: 'easy',
    question: 'Which word is a synonym (same meaning) for "happy"?',
    answers: ['Sad', 'Angry', 'Joyful', 'Tired'],
    correctIndex: 2,
    explanation: '"Joyful" is a synonym for "happy" — both mean feeling pleased and content. Synonyms are words with similar meanings.',
    hint: 'A synonym means the same thing.',
    tags: ['synonyms', 'vocabulary'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'language_easy_002',
    subject: 'language',
    difficulty: 'easy',
    question: 'What is the antonym (opposite) of "hot"?',
    answers: ['Warm', 'Cold', 'Spicy', 'Bright'],
    correctIndex: 1,
    explanation: '"Cold" is the antonym (opposite) of "hot." Antonyms are words with opposite meanings.',
    tags: ['antonyms', 'vocabulary'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'language_easy_003',
    subject: 'language',
    difficulty: 'easy',
    question: 'Which word in this sentence is a noun? "The cat sat on the mat."',
    answers: ['sat', 'on', 'the', 'cat'],
    correctIndex: 3,
    explanation: '"Cat" is a noun — it names a thing (an animal). Nouns are naming words for people, places, things, or ideas.',
    hint: 'A noun is a naming word.',
    tags: ['grammar', 'parts of speech', 'nouns'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'language_easy_004',
    subject: 'language',
    difficulty: 'easy',
    question: 'Which of these words rhymes with "cake"?',
    answers: ['Back', 'Lake', 'Clock', 'Milk'],
    correctIndex: 1,
    explanation: '"Lake" rhymes with "cake" — both end with the "-ake" sound. Rhyming words share the same ending sound.',
    tags: ['rhyming', 'phonics'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'language_easy_005',
    subject: 'language',
    difficulty: 'easy',
    question: 'Which word is a verb (action word)?',
    answers: ['Beautiful', 'Running', 'Blue', 'Table'],
    correctIndex: 1,
    explanation: '"Running" is a verb — it describes an action. Verbs are action words like run, jump, eat, or sleep.',
    tags: ['grammar', 'verbs', 'parts of speech'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'language_easy_006',
    subject: 'language',
    difficulty: 'easy',
    question: 'What punctuation mark goes at the end of a question?',
    answers: ['Period (.)', 'Exclamation mark (!)', 'Question mark (?)', 'Comma (,)'],
    correctIndex: 2,
    explanation: 'A question mark (?) goes at the end of a sentence that asks a question. For example: "What is your name?"',
    tags: ['grammar', 'punctuation'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'language_easy_007',
    subject: 'language',
    difficulty: 'easy',
    question: 'Which word is a synonym for "big"?',
    answers: ['Tiny', 'Small', 'Large', 'Short'],
    correctIndex: 2,
    explanation: '"Large" is a synonym for "big" — both mean of great size.',
    tags: ['synonyms', 'vocabulary'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'language_easy_008',
    subject: 'language',
    difficulty: 'easy',
    question: 'Which word completes the sentence correctly? "She ___ to the store yesterday."',
    answers: ['go', 'goes', 'went', 'going'],
    correctIndex: 2,
    explanation: '"Went" is the past tense of "go." Since the sentence says "yesterday," we need the past tense.',
    tags: ['grammar', 'verbs', 'tense'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'language_easy_009',
    subject: 'language',
    difficulty: 'easy',
    question: 'What is the antonym (opposite) of "tall"?',
    answers: ['Big', 'Wide', 'Short', 'Long'],
    correctIndex: 2,
    explanation: '"Short" is the antonym of "tall." Antonyms are words with opposite meanings.',
    tags: ['antonyms', 'vocabulary'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'language_easy_010',
    subject: 'language',
    difficulty: 'easy',
    question: 'Which sentence uses correct capitalization?',
    answers: ['my name is Alex.', 'My name is alex.', 'My name is Alex.', 'my Name Is Alex.'],
    correctIndex: 2,
    explanation: '"My name is Alex." is correct. Sentences start with a capital letter, and proper names (like Alex) are always capitalized.',
    tags: ['grammar', 'capitalization'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'language_easy_011',
    subject: 'language',
    difficulty: 'easy',
    question: 'Which word is an adjective (describing word)?',
    answers: ['Jump', 'Slowly', 'Purple', 'Banana'],
    correctIndex: 2,
    explanation: '"Purple" is an adjective — it describes what something looks like. Adjectives describe nouns (like "a purple flower").',
    tags: ['grammar', 'adjectives', 'parts of speech'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'language_easy_012',
    subject: 'language',
    difficulty: 'easy',
    question: 'How many syllables does the word "elephant" have?',
    answers: ['2', '3', '4', '5'],
    correctIndex: 1,
    explanation: '"Elephant" has 3 syllables: el-e-phant. Each syllable contains a vowel sound.',
    hint: 'Clap as you say each part.',
    tags: ['phonics', 'syllables'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'language_easy_013',
    subject: 'language',
    difficulty: 'easy',
    question: 'What is the plural of "child"?',
    answers: ['Childs', 'Childes', 'Childrens', 'Children'],
    correctIndex: 3,
    explanation: 'The plural of "child" is "children" — an irregular plural. Not all words add -s to become plural.',
    tags: ['grammar', 'plurals'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'language_easy_014',
    subject: 'language',
    difficulty: 'easy',
    question: 'Which word rhymes with "night"?',
    answers: ['Need', 'Kneel', 'Light', 'King'],
    correctIndex: 2,
    explanation: '"Light" rhymes with "night" — both end with the "-ight" sound.',
    tags: ['rhyming', 'phonics'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'language_easy_015',
    subject: 'language',
    difficulty: 'easy',
    question: 'Which word is a pronoun that replaces "Maria"?',
    answers: ['They', 'He', 'She', 'It'],
    correctIndex: 2,
    explanation: '"She" is the pronoun used for a female person. "Maria went to the park" becomes "She went to the park."',
    tags: ['grammar', 'pronouns', 'parts of speech'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'language_easy_016',
    subject: 'language',
    difficulty: 'easy',
    question: 'What does the word "swift" mean?',
    answers: ['Slow', 'Fast', 'Heavy', 'Quiet'],
    correctIndex: 1,
    explanation: '"Swift" means fast or quick. A swift runner moves very quickly.',
    tags: ['vocabulary', 'synonyms'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'language_easy_017',
    subject: 'language',
    difficulty: 'easy',
    question: 'Which sentence is a complete sentence?',
    answers: ['Running fast.', 'The big dog.', 'The dog ran fast.', 'Because it was raining.'],
    correctIndex: 2,
    explanation: '"The dog ran fast" is a complete sentence — it has a subject (the dog) and a verb (ran). A complete sentence must have both.',
    tags: ['grammar', 'sentences'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'language_easy_018',
    subject: 'language',
    difficulty: 'easy',
    question: 'What is a noun?',
    answers: ['An action word', 'A word that describes how something is done', 'A naming word for a person, place, thing, or idea', 'A connecting word'],
    correctIndex: 2,
    explanation: 'A noun is a naming word. It names people (teacher), places (park), things (book), or ideas (freedom).',
    tags: ['grammar', 'nouns', 'parts of speech'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'language_easy_019',
    subject: 'language',
    difficulty: 'easy',
    question: 'Which word is the antonym of "begin"?',
    answers: ['Start', 'Continue', 'End', 'Create'],
    correctIndex: 2,
    explanation: '"End" is the antonym of "begin." Begin means to start, and end means to finish.',
    tags: ['antonyms', 'vocabulary'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'language_easy_020',
    subject: 'language',
    difficulty: 'easy',
    question: 'What does the prefix "un-" mean in the word "unhappy"?',
    answers: ['Very', 'Again', 'Not', 'Too much'],
    correctIndex: 2,
    explanation: 'The prefix "un-" means "not." So "unhappy" means "not happy." Other examples: unfair, unkind, unusual.',
    tags: ['vocabulary', 'prefixes'],
    xpReward: 10,
    timeLimit: 30,
  },

  // ─── MEDIUM ─────────────────────────────────────────────────────────────────
  {
    id: 'language_medium_001',
    subject: 'language',
    difficulty: 'medium',
    question: 'What is a simile?',
    answers: ['A word that sounds like another word', 'A comparison using "like" or "as"', 'A word with multiple meanings', 'A group of words with hidden meaning'],
    correctIndex: 1,
    explanation: 'A simile compares two things using "like" or "as." Example: "She runs like the wind" or "He is as brave as a lion."',
    hint: 'It uses "like" or "as" to compare.',
    tags: ['figurative language', 'literary devices'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'language_medium_002',
    subject: 'language',
    difficulty: 'medium',
    question: 'Identify the conjunction in: "I wanted to go outside, but it was raining."',
    answers: ['wanted', 'outside', 'but', 'raining'],
    correctIndex: 2,
    explanation: '"But" is a conjunction — it joins two clauses together. Common conjunctions include: and, but, or, so, yet, for, nor.',
    tags: ['grammar', 'conjunctions', 'parts of speech'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'language_medium_003',
    subject: 'language',
    difficulty: 'medium',
    question: 'What is an adverb?',
    answers: ['A word that names a person or thing', 'A word that modifies a verb, adjective, or another adverb', 'A word that connects two clauses', 'A word that takes the place of a noun'],
    correctIndex: 1,
    explanation: 'An adverb modifies (describes) a verb, adjective, or another adverb. Many end in "-ly": quickly, quietly, softly. Example: "She ran quickly."',
    tags: ['grammar', 'adverbs', 'parts of speech'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'language_medium_004',
    subject: 'language',
    difficulty: 'medium',
    question: 'What is a metaphor?',
    answers: ['A comparison using "like" or "as"', 'Giving human qualities to non-human things', 'A direct comparison without using "like" or "as"', 'Words that sound like the things they describe'],
    correctIndex: 2,
    explanation: 'A metaphor makes a direct comparison without using "like" or "as." Example: "Life is a journey" or "The classroom was a zoo."',
    tags: ['figurative language', 'literary devices'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'language_medium_005',
    subject: 'language',
    difficulty: 'medium',
    question: 'Which sentence is in the passive voice?',
    answers: ['The chef cooked the meal.', 'The meal was cooked by the chef.', 'The chef is cooking the meal.', 'The chef will cook the meal.'],
    correctIndex: 1,
    explanation: '"The meal was cooked by the chef" is passive — the subject (meal) receives the action. Active voice: the subject performs the action. Passive: the subject receives it.',
    tags: ['grammar', 'voice'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'language_medium_006',
    subject: 'language',
    difficulty: 'medium',
    question: 'What does "context clues" mean in reading?',
    answers: ['Looking up words in a dictionary', 'Using surrounding words and sentences to figure out an unknown word\'s meaning', 'Reading only the important words', 'Skipping unfamiliar words'],
    correctIndex: 1,
    explanation: 'Context clues are hints in the text around an unfamiliar word that help you understand its meaning without a dictionary.',
    tags: ['reading comprehension', 'vocabulary'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'language_medium_007',
    subject: 'language',
    difficulty: 'medium',
    question: 'What is personification?',
    answers: ['Comparing two unlike things', 'Exaggerating for effect', 'Giving human qualities to non-human things', 'Words that imitate sounds'],
    correctIndex: 2,
    explanation: 'Personification gives human characteristics to objects, animals, or ideas. Example: "The wind whispered through the trees" or "The stars danced in the sky."',
    tags: ['figurative language', 'literary devices'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'language_medium_008',
    subject: 'language',
    difficulty: 'medium',
    question: 'What is the difference between a phrase and a clause?',
    answers: ['There is no difference', 'A clause has a subject and a verb; a phrase does not', 'A phrase has a subject and verb; a clause does not', 'A clause is always shorter than a phrase'],
    correctIndex: 1,
    explanation: 'A clause has both a subject and a verb (e.g., "she sings"). A phrase is a group of words without both (e.g., "in the morning").',
    tags: ['grammar', 'sentence structure'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'language_medium_009',
    subject: 'language',
    difficulty: 'medium',
    question: 'Which word has a negative connotation (unpleasant feeling)?',
    answers: ['Slender', 'Scrawny', 'Thin', 'Lean'],
    correctIndex: 1,
    explanation: '"Scrawny" carries a negative connotation suggesting unpleasant thinness. "Slender," "thin," and "lean" are more neutral. Connotation is the emotional feeling a word carries beyond its dictionary meaning.',
    tags: ['vocabulary', 'connotation'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'language_medium_010',
    subject: 'language',
    difficulty: 'medium',
    question: 'What is a compound sentence?',
    answers: ['A sentence with one independent clause', 'Two or more independent clauses joined by a conjunction', 'A sentence with a dependent clause only', 'A very long sentence with many adjectives'],
    correctIndex: 1,
    explanation: 'A compound sentence has two independent clauses joined by a conjunction (and, but, so, or). Example: "I wanted pizza, but we ordered pasta."',
    tags: ['grammar', 'sentence structure'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'language_medium_011',
    subject: 'language',
    difficulty: 'medium',
    question: 'What does the suffix "-tion" mean in the word "creation"?',
    answers: ['Without', 'Full of', 'The act or state of', 'One who'],
    correctIndex: 2,
    explanation: 'The suffix "-tion" means "the act or state of." Creation = the act of creating. Other examples: education (act of educating), celebration (act of celebrating).',
    tags: ['vocabulary', 'suffixes'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'language_medium_012',
    subject: 'language',
    difficulty: 'medium',
    question: 'What is alliteration?',
    answers: ['Words that rhyme at the end of lines', 'The repetition of the same consonant sound at the start of nearby words', 'A word that sounds like what it means', 'Exaggeration used for humor'],
    correctIndex: 1,
    explanation: 'Alliteration is the repetition of the same starting sound. Example: "Peter Piper picked a peck of pickled peppers." It is used to create rhythm and emphasis.',
    tags: ['literary devices', 'figurative language'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'language_medium_013',
    subject: 'language',
    difficulty: 'medium',
    question: 'Which type of sentence expresses a strong emotion or command?',
    answers: ['Declarative', 'Interrogative', 'Exclamatory', 'Imperative'],
    correctIndex: 2,
    explanation: 'An exclamatory sentence expresses strong feeling and ends with an exclamation mark. Example: "What a wonderful surprise!" An imperative sentence gives a command: "Close the door."',
    tags: ['grammar', 'sentence types'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'language_medium_014',
    subject: 'language',
    difficulty: 'medium',
    question: 'What is the main purpose of a topic sentence in a paragraph?',
    answers: ['To provide examples and details', 'To conclude the paragraph', 'To state the main idea of the paragraph', 'To introduce a new topic for the next paragraph'],
    correctIndex: 2,
    explanation: 'A topic sentence states the main idea of a paragraph. It is usually the first sentence and tells the reader what the paragraph will be about.',
    tags: ['writing', 'reading comprehension'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'language_medium_015',
    subject: 'language',
    difficulty: 'medium',
    question: 'Which sentence contains a preposition?',
    answers: ['The dog barked loudly.', 'She quickly ran home.', 'The book is on the table.', 'He smiled and waved.'],
    correctIndex: 2,
    explanation: '"On" is a preposition in "The book is on the table." Prepositions show the relationship between a noun and another word (on, in, under, beside, between).',
    tags: ['grammar', 'prepositions', 'parts of speech'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'language_medium_016',
    subject: 'language',
    difficulty: 'medium',
    question: 'What is the meaning of the word "benevolent"?',
    answers: ['Cruel and mean', 'Kind and generous', 'Loud and boastful', 'Shy and timid'],
    correctIndex: 1,
    explanation: '"Benevolent" means kind, generous, and well-meaning. "Bene" comes from Latin meaning "good," and "vole" means "wishing." So benevolent = wishing good.',
    tags: ['vocabulary', 'word roots'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'language_medium_017',
    subject: 'language',
    difficulty: 'medium',
    question: 'What is onomatopoeia?',
    answers: ['A comparison using "like" or "as"', 'Giving human qualities to objects', 'Words that sound like the things they describe', 'Repeating a sound at the start of words'],
    correctIndex: 2,
    explanation: 'Onomatopoeia refers to words that imitate the sounds they describe. Examples: buzz, crash, sizzle, moo, bang, hiss.',
    tags: ['literary devices', 'figurative language'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'language_medium_018',
    subject: 'language',
    difficulty: 'medium',
    question: 'What does an author\'s "point of view" or "perspective" mean?',
    answers: ['The plot of the story', 'The physical location where a story takes place', 'The narrator\'s position and how the story is told', 'The lesson or message of a story'],
    correctIndex: 2,
    explanation: 'Point of view is the perspective from which a story is told. First person uses "I"; third person uses "he/she/they." The narrator\'s perspective shapes what readers know and feel.',
    tags: ['reading comprehension', 'literary devices'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'language_medium_019',
    subject: 'language',
    difficulty: 'medium',
    question: 'Which word correctly completes this sentence? "Neither the students nor the teacher ___ ready."',
    answers: ['were', 'are', 'was', 'been'],
    correctIndex: 2,
    explanation: 'When using "neither...nor," the verb agrees with the closer subject. "Teacher" is singular, so the verb is "was." This is subject-verb agreement.',
    tags: ['grammar', 'subject-verb agreement'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'language_medium_020',
    subject: 'language',
    difficulty: 'medium',
    question: 'What is the difference between a synonym and an antonym?',
    answers: ['Synonyms are nouns; antonyms are verbs', 'Synonyms have the same meaning; antonyms have opposite meanings', 'Synonyms rhyme; antonyms do not', 'They are the same thing'],
    correctIndex: 1,
    explanation: 'A synonym has a similar meaning (happy/joyful). An antonym has the opposite meaning (happy/sad). Both are important vocabulary tools.',
    tags: ['vocabulary', 'synonyms', 'antonyms'],
    xpReward: 20,
    timeLimit: 25,
  },

  // ─── HARD ────────────────────────────────────────────────────────────────────
  {
    id: 'language_hard_001',
    subject: 'language',
    difficulty: 'hard',
    question: 'What is the difference between a restrictive and a non-restrictive clause?',
    answers: ['Restrictive clauses are longer', 'Restrictive clauses are essential to the sentence meaning; non-restrictive add extra information and use commas', 'Non-restrictive clauses change the sentence meaning', 'There is no difference'],
    correctIndex: 1,
    explanation: 'A restrictive clause is essential: "The book that I lost was a gift" (specifies which book). Non-restrictive adds extra info with commas: "The book, which was blue, was a gift."',
    tags: ['grammar', 'advanced grammar'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'language_hard_002',
    subject: 'language',
    difficulty: 'hard',
    question: 'What is dramatic irony?',
    answers: ['When a character says the opposite of what they mean', 'When the audience knows something a character does not', 'When events turn out differently than expected', 'When a story has an unexpected ending'],
    correctIndex: 1,
    explanation: 'Dramatic irony occurs when the audience knows information that a character in the story does not. This creates tension or humor — like watching a character walk into a surprise party.',
    tags: ['literary devices', 'irony'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'language_hard_003',
    subject: 'language',
    difficulty: 'hard',
    question: 'What is the difference between "affect" and "effect"?',
    answers: ['"Affect" is a noun; "effect" is a verb', '"Affect" is usually a verb (to influence); "effect" is usually a noun (the result)', 'They mean the same thing', '"Effect" is always a verb; "affect" is an adjective'],
    correctIndex: 1,
    explanation: '"Affect" (verb): "The rain affected our plans." "Effect" (noun): "The rain had a big effect on our plans." Memory tip: Affect is the Action; Effect is the End result.',
    tags: ['grammar', 'commonly confused words'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'language_hard_004',
    subject: 'language',
    difficulty: 'hard',
    question: 'What is an oxymoron?',
    answers: ['A very long and complex word', 'Two contradictory words placed together', 'Saying the opposite of what you mean', 'Extreme exaggeration for effect'],
    correctIndex: 1,
    explanation: 'An oxymoron combines two contradictory words. Examples: "deafening silence," "bittersweet," "living death," "open secret." It creates a striking paradoxical expression.',
    tags: ['literary devices', 'figurative language'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'language_hard_005',
    subject: 'language',
    difficulty: 'hard',
    question: 'In grammar, what is a dangling modifier?',
    answers: ['An adjective with no noun to modify', 'A modifier placed next to a word it does not actually modify, creating confusion', 'A verb without a subject', 'Too many adjectives in one sentence'],
    correctIndex: 1,
    explanation: 'A dangling modifier is confusingly placed. Example: "Eating lunch, the bell rang." (The bell wasn\'t eating lunch!) Correct: "While I was eating lunch, the bell rang."',
    tags: ['grammar', 'advanced grammar'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'language_hard_006',
    subject: 'language',
    difficulty: 'hard',
    question: 'What is the word "ephemeral" closest in meaning to?',
    answers: ['Eternal and permanent', 'Short-lived and temporary', 'Ghostly and mysterious', 'Enormous and impressive'],
    correctIndex: 1,
    explanation: '"Ephemeral" means lasting a very short time. From the Greek "ephemeros" meaning "lasting only a day." Example: "The beauty of cherry blossoms is ephemeral."',
    tags: ['vocabulary', 'advanced vocabulary'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'language_hard_007',
    subject: 'language',
    difficulty: 'hard',
    question: 'What is the subjunctive mood in English?',
    answers: ['A past tense verb form', 'A verb form used to express wishes, hypotheticals, or conditions contrary to fact', 'The same as the imperative mood', 'A future tense verb form'],
    correctIndex: 1,
    explanation: 'The subjunctive expresses wishes, hypotheticals, or unreal conditions. Examples: "I wish I were taller." (not "was") or "If she were president..." The key word is "were" instead of "was."',
    tags: ['grammar', 'advanced grammar', 'mood'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'language_hard_008',
    subject: 'language',
    difficulty: 'hard',
    question: 'What is "situational irony"?',
    answers: ['When a speaker means the opposite of what they say', 'When the audience knows more than the character', 'When events turn out the opposite of what was expected', 'When a story repeats the same situation twice'],
    correctIndex: 2,
    explanation: 'Situational irony is when the actual outcome of a situation is the opposite of what was expected. Example: A firefighter whose house burns down, or a police station being robbed.',
    tags: ['literary devices', 'irony'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'language_hard_009',
    subject: 'language',
    difficulty: 'hard',
    question: 'What is an extended metaphor?',
    answers: ['A metaphor that uses very descriptive language', 'A metaphor sustained across a whole passage or work', 'A metaphor with three or more comparisons listed', 'A metaphor that uses simile language'],
    correctIndex: 1,
    explanation: 'An extended metaphor is one that is developed throughout an entire passage, poem, or story. Rather than a single comparison, the author keeps building on the metaphor.',
    tags: ['literary devices', 'figurative language'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'language_hard_010',
    subject: 'language',
    difficulty: 'hard',
    question: 'What does it mean for a word to be "polysemous"?',
    answers: ['It sounds like another word', 'It has multiple related meanings', 'It is borrowed from another language', 'It has no plural form'],
    correctIndex: 1,
    explanation: 'A polysemous word has multiple related meanings. The word "bank" is polysemous: a river bank, a bank for money, to bank (tilt), to bank on (rely on). Context determines meaning.',
    tags: ['vocabulary', 'advanced vocabulary', 'semantics'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'language_hard_011',
    subject: 'language',
    difficulty: 'hard',
    question: 'What is a "foil" in literature?',
    answers: ['The setting of a story', 'A character who contrasts with the main character to highlight certain traits', 'The turning point of a plot', 'An unreliable narrator'],
    correctIndex: 1,
    explanation: 'A foil is a character whose traits contrast with the main character\'s, making those traits stand out more clearly. Example: Sherlock Holmes\'s brilliance is highlighted by his foil, Dr. Watson\'s more ordinary nature.',
    tags: ['literary devices', 'reading comprehension'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'language_hard_012',
    subject: 'language',
    difficulty: 'hard',
    question: 'What is the difference between denotation and connotation?',
    answers: ['Denotation is pronunciation; connotation is spelling', 'Denotation is the literal dictionary meaning; connotation is the emotional associations a word carries', 'Denotation is for verbs; connotation is for nouns', 'They mean the same thing'],
    correctIndex: 1,
    explanation: 'Denotation is the exact dictionary definition. Connotation is the emotional tone or associations. "Snake" denotes a reptile, but connotes danger or deception. Authors choose words carefully for both.',
    tags: ['vocabulary', 'semantics', 'advanced vocabulary'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'language_hard_013',
    subject: 'language',
    difficulty: 'hard',
    question: 'What is a "stream of consciousness" writing style?',
    answers: ['Writing about nature and water', 'A narration that directly follows a character\'s flowing thoughts and feelings', 'Writing that follows strict poetic rules', 'A factual, journalistic writing style'],
    correctIndex: 1,
    explanation: 'Stream of consciousness is a narrative technique where writing follows the natural flow of a character\'s thoughts — often jumping between ideas as the mind does. Used famously by James Joyce and Virginia Woolf.',
    tags: ['literary devices', 'writing styles'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'language_hard_014',
    subject: 'language',
    difficulty: 'hard',
    question: 'What is "hyperbole"?',
    answers: ['A comparison using "like" or "as"', 'Deliberate exaggeration for emphasis or humor', 'Saying the opposite of what you mean', 'Words that sound like their meaning'],
    correctIndex: 1,
    explanation: 'Hyperbole is extreme exaggeration used for effect. Examples: "I\'ve told you a million times!" or "I\'m so hungry I could eat a horse!" It is not meant to be taken literally.',
    tags: ['figurative language', 'literary devices'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'language_hard_015',
    subject: 'language',
    difficulty: 'hard',
    question: 'In the sentence "Having finished the test, the students celebrated," what is the grammatical issue?',
    answers: ['Wrong verb tense', 'Dangling participle — it implies the students finished, but could be misread', 'Missing comma', 'No issue; the sentence is correct'],
    correctIndex: 3,
    explanation: 'Actually, this sentence is correctly written — "Having finished the test" clearly modifies "the students." The sentence is grammatically correct.',
    tags: ['grammar', 'advanced grammar'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'language_hard_016',
    subject: 'language',
    difficulty: 'hard',
    question: 'What is the term for the central message or insight about life that a literary work conveys?',
    answers: ['Plot', 'Setting', 'Theme', 'Motif'],
    correctIndex: 2,
    explanation: 'The theme is the central idea or insight about life expressed in a work. Unlike a "topic" (what it\'s about), a theme is an observation about life, such as "courage overcomes fear."',
    tags: ['literary devices', 'reading comprehension'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'language_hard_017',
    subject: 'language',
    difficulty: 'hard',
    question: 'What is "verbal irony"?',
    answers: ['Using a verb incorrectly in a sentence', 'When events turn out opposite to expectations', 'Saying the opposite of what you mean, often sarcastically', 'When a reader knows more than a character'],
    correctIndex: 2,
    explanation: 'Verbal irony is saying the opposite of what you mean. Sarcasm is a form of verbal irony. Example: Saying "Oh great, another Monday!" when you actually dislike Mondays.',
    tags: ['literary devices', 'irony'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'language_hard_018',
    subject: 'language',
    difficulty: 'hard',
    question: 'What word best replaces "said" to show that a character spoke quietly and fearfully?',
    answers: ['Shouted', 'Whispered', 'Declared', 'Announced'],
    correctIndex: 1,
    explanation: '"Whispered" conveys speaking quietly, often with fear or secrecy. Strong writers choose precise words instead of "said" to reveal a character\'s emotion and tone.',
    tags: ['vocabulary', 'writing', 'word choice'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'language_hard_019',
    subject: 'language',
    difficulty: 'hard',
    question: 'What is an "unreliable narrator"?',
    answers: ['A narrator who speaks in first person', 'A narrator who forgets details of the story', 'A narrator whose credibility is compromised, so the reader cannot fully trust their account', 'A narrator who tells the story from multiple perspectives'],
    correctIndex: 2,
    explanation: 'An unreliable narrator is one whose account cannot be fully trusted — due to bias, limited knowledge, mental state, or dishonesty. Readers must read between the lines to find the truth.',
    tags: ['literary devices', 'reading comprehension'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'language_hard_020',
    subject: 'language',
    difficulty: 'hard',
    question: 'What does the Latin root "bene" (as in "benefit," "benevolent") mean?',
    answers: ['Under', 'Good or well', 'Two', 'Against'],
    correctIndex: 1,
    explanation: '"Bene" is a Latin root meaning "good" or "well." Benefit = good result. Benevolent = wishing good. Benign = gentle/not harmful. Knowing roots helps unlock the meaning of many English words.',
    tags: ['vocabulary', 'word roots', 'etymology'],
    xpReward: 35,
    timeLimit: 20,
  },
]
