import type { Question } from '../types'

export const MATH_QUESTIONS: Question[] = [
  // ─── EASY ───────────────────────────────────────────────────────────────────
  {
    id: 'math_easy_001',
    subject: 'math',
    difficulty: 'easy',
    question: 'What is 7 + 5?',
    answers: ['10', '11', '12', '13'],
    correctIndex: 2,
    explanation: '7 + 5 = 12. You can count up 5 from 7: 8, 9, 10, 11, 12.',
    hint: 'Count on your fingers starting from 7.',
    tags: ['addition'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'math_easy_002',
    subject: 'math',
    difficulty: 'easy',
    question: 'What is 15 - 8?',
    answers: ['5', '6', '7', '8'],
    correctIndex: 2,
    explanation: '15 - 8 = 7. Starting at 15, count back 8 steps to reach 7.',
    hint: 'Think: 8 + ? = 15.',
    tags: ['subtraction'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'math_easy_003',
    subject: 'math',
    difficulty: 'easy',
    question: 'What is 4 × 3?',
    answers: ['7', '10', '12', '14'],
    correctIndex: 2,
    explanation: '4 × 3 = 12. Multiplication is repeated addition: 4 + 4 + 4 = 12.',
    hint: 'Add 4 three times.',
    tags: ['multiplication'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'math_easy_004',
    subject: 'math',
    difficulty: 'easy',
    question: 'How many sides does a triangle have?',
    answers: ['2', '3', '4', '5'],
    correctIndex: 1,
    explanation: 'A triangle has 3 sides. The word "tri" means three, just like tricycle has 3 wheels.',
    hint: '"Tri" means three.',
    tags: ['shapes', 'geometry'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'math_easy_005',
    subject: 'math',
    difficulty: 'easy',
    question: 'What is half of 18?',
    answers: ['7', '8', '9', '10'],
    correctIndex: 2,
    explanation: 'Half of 18 is 9. Dividing by 2 gives half: 18 ÷ 2 = 9.',
    hint: 'Divide 18 by 2.',
    tags: ['fractions', 'division'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'math_easy_006',
    subject: 'math',
    difficulty: 'easy',
    question: 'What comes next? 2, 4, 6, 8, ___',
    answers: ['9', '10', '11', '12'],
    correctIndex: 1,
    explanation: 'The pattern adds 2 each time (even numbers). After 8 comes 10.',
    hint: 'Each number is 2 more than the last.',
    tags: ['patterns', 'counting'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'math_easy_007',
    subject: 'math',
    difficulty: 'easy',
    question: 'Which fraction is bigger: 1/2 or 1/4?',
    answers: ['1/4', '1/2', 'They are equal', 'Cannot tell'],
    correctIndex: 1,
    explanation: '1/2 is bigger. If you cut a pizza into 2 pieces, each piece is larger than if you cut it into 4 pieces.',
    hint: 'Imagine cutting a pizza.',
    tags: ['fractions'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'math_easy_008',
    subject: 'math',
    difficulty: 'easy',
    question: 'What is 6 × 2?',
    answers: ['8', '10', '12', '14'],
    correctIndex: 2,
    explanation: '6 × 2 = 12. Think of it as 2 groups of 6: 6 + 6 = 12.',
    hint: 'Add 6 twice.',
    tags: ['multiplication'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'math_easy_009',
    subject: 'math',
    difficulty: 'easy',
    question: 'How many corners does a rectangle have?',
    answers: ['2', '3', '4', '6'],
    correctIndex: 2,
    explanation: 'A rectangle has 4 corners (also called vertices). It also has 4 sides.',
    hint: 'Count the pointy corners on a door.',
    tags: ['shapes', 'geometry'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'math_easy_010',
    subject: 'math',
    difficulty: 'easy',
    question: 'What is 20 + 35?',
    answers: ['45', '50', '55', '60'],
    correctIndex: 2,
    explanation: '20 + 35 = 55. Add the tens: 20 + 30 = 50, then add 5 more: 50 + 5 = 55.',
    tags: ['addition'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'math_easy_011',
    subject: 'math',
    difficulty: 'easy',
    question: 'If you have 10 apples and give away 3, how many do you have left?',
    answers: ['5', '6', '7', '8'],
    correctIndex: 2,
    explanation: '10 - 3 = 7. Subtraction tells us how many remain after giving some away.',
    hint: 'Start at 10 and count back 3.',
    tags: ['subtraction', 'word problems'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'math_easy_012',
    subject: 'math',
    difficulty: 'easy',
    question: 'What is 9 + 9?',
    answers: ['16', '17', '18', '19'],
    correctIndex: 2,
    explanation: '9 + 9 = 18. Doubling 9 gives 18. You can also think of it as 10 + 10 - 2 = 18.',
    tags: ['addition'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'math_easy_013',
    subject: 'math',
    difficulty: 'easy',
    question: 'How many minutes are in one hour?',
    answers: ['30', '45', '60', '100'],
    correctIndex: 2,
    explanation: 'There are 60 minutes in one hour. A clock face shows 60 minute marks.',
    tags: ['time', 'counting'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'math_easy_014',
    subject: 'math',
    difficulty: 'easy',
    question: 'What is 5 × 5?',
    answers: ['20', '22', '25', '30'],
    correctIndex: 2,
    explanation: '5 × 5 = 25. When multiplying 5 by itself, the answer always ends in 5 or 0.',
    tags: ['multiplication'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'math_easy_015',
    subject: 'math',
    difficulty: 'easy',
    question: 'What is 100 - 45?',
    answers: ['45', '55', '65', '75'],
    correctIndex: 1,
    explanation: '100 - 45 = 55. You can think: 45 + 55 = 100.',
    tags: ['subtraction'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'math_easy_016',
    subject: 'math',
    difficulty: 'easy',
    question: 'Which number is even?',
    answers: ['7', '11', '14', '19'],
    correctIndex: 2,
    explanation: '14 is even. Even numbers can be divided by 2 with no remainder. They end in 0, 2, 4, 6, or 8.',
    tags: ['counting', 'number properties'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'math_easy_017',
    subject: 'math',
    difficulty: 'easy',
    question: 'If there are 3 baskets with 4 oranges each, how many oranges in total?',
    answers: ['7', '10', '12', '16'],
    correctIndex: 2,
    explanation: '3 × 4 = 12. Multiplication helps us count equal groups quickly.',
    hint: 'Multiply the number of baskets by oranges in each.',
    tags: ['multiplication', 'word problems'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'math_easy_018',
    subject: 'math',
    difficulty: 'easy',
    question: 'What shape has no corners and is perfectly round?',
    answers: ['Square', 'Triangle', 'Circle', 'Rectangle'],
    correctIndex: 2,
    explanation: 'A circle has no corners or straight sides. Every point on its edge is the same distance from the center.',
    tags: ['shapes', 'geometry'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'math_easy_019',
    subject: 'math',
    difficulty: 'easy',
    question: 'What is 3 + 4 + 5?',
    answers: ['10', '11', '12', '13'],
    correctIndex: 2,
    explanation: '3 + 4 + 5 = 12. Add in steps: 3 + 4 = 7, then 7 + 5 = 12.',
    tags: ['addition'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'math_easy_020',
    subject: 'math',
    difficulty: 'easy',
    question: 'What is one quarter (1/4) of 20?',
    answers: ['4', '5', '6', '8'],
    correctIndex: 1,
    explanation: '1/4 of 20 is 5. Dividing 20 into 4 equal parts gives 5 in each part: 20 ÷ 4 = 5.',
    tags: ['fractions'],
    xpReward: 10,
    timeLimit: 30,
  },

  // ─── MEDIUM ─────────────────────────────────────────────────────────────────
  {
    id: 'math_medium_001',
    subject: 'math',
    difficulty: 'medium',
    question: 'What is 144 ÷ 12?',
    answers: ['10', '11', '12', '13'],
    correctIndex: 2,
    explanation: '144 ÷ 12 = 12. This is a perfect square: 12 × 12 = 144.',
    tags: ['division'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'math_medium_002',
    subject: 'math',
    difficulty: 'medium',
    question: 'What is the perimeter of a square with sides of 7 cm?',
    answers: ['14 cm', '21 cm', '28 cm', '49 cm'],
    correctIndex: 2,
    explanation: 'Perimeter = 4 × side = 4 × 7 = 28 cm. Perimeter is the total distance around a shape.',
    hint: 'Add all 4 sides together.',
    tags: ['geometry', 'perimeter'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'math_medium_003',
    subject: 'math',
    difficulty: 'medium',
    question: 'What is 3/4 + 1/4?',
    answers: ['1/2', '3/8', '1', '4/8'],
    correctIndex: 2,
    explanation: '3/4 + 1/4 = 4/4 = 1. When fractions have the same denominator, just add the numerators.',
    tags: ['fractions', 'addition'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'math_medium_004',
    subject: 'math',
    difficulty: 'medium',
    question: 'If x + 7 = 15, what is x?',
    answers: ['6', '7', '8', '9'],
    correctIndex: 2,
    explanation: 'x = 15 - 7 = 8. To find x, subtract 7 from both sides of the equation.',
    hint: 'What number plus 7 equals 15?',
    tags: ['algebra'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'math_medium_005',
    subject: 'math',
    difficulty: 'medium',
    question: 'What is 0.5 written as a fraction?',
    answers: ['1/4', '1/3', '1/2', '2/3'],
    correctIndex: 2,
    explanation: '0.5 = 1/2. The decimal 0.5 means 5 tenths, which simplifies to one half.',
    tags: ['decimals', 'fractions'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'math_medium_006',
    subject: 'math',
    difficulty: 'medium',
    question: 'What is the area of a rectangle that is 6 cm wide and 9 cm long?',
    answers: ['30 cm²', '45 cm²', '54 cm²', '60 cm²'],
    correctIndex: 2,
    explanation: 'Area = length × width = 9 × 6 = 54 cm². Area tells us how much surface a shape covers.',
    tags: ['geometry', 'area', 'multiplication'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'math_medium_007',
    subject: 'math',
    difficulty: 'medium',
    question: 'What is 25% of 80?',
    answers: ['15', '20', '25', '40'],
    correctIndex: 1,
    explanation: '25% of 80 = 80 ÷ 4 = 20. Because 25% means one quarter, dividing by 4 gives the answer.',
    hint: '25% = 1/4. Divide by 4.',
    tags: ['percentages'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'math_medium_008',
    subject: 'math',
    difficulty: 'medium',
    question: 'What is 7 × 8?',
    answers: ['48', '54', '56', '64'],
    correctIndex: 2,
    explanation: '7 × 8 = 56. This is one of the trickiest multiplication facts. Try: 7 × 8 = 56 (7, 8, 56 — they go in order!).',
    tags: ['multiplication'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'math_medium_009',
    subject: 'math',
    difficulty: 'medium',
    question: 'A train travels 60 km/h for 3 hours. How far does it travel?',
    answers: ['120 km', '160 km', '180 km', '200 km'],
    correctIndex: 2,
    explanation: 'Distance = speed × time = 60 × 3 = 180 km.',
    tags: ['word problems', 'multiplication'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'math_medium_010',
    subject: 'math',
    difficulty: 'medium',
    question: 'What is 2/5 of 50?',
    answers: ['10', '15', '20', '25'],
    correctIndex: 2,
    explanation: '2/5 of 50 = (50 ÷ 5) × 2 = 10 × 2 = 20.',
    tags: ['fractions', 'multiplication'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'math_medium_011',
    subject: 'math',
    difficulty: 'medium',
    question: 'What is the value of 3² (3 squared)?',
    answers: ['6', '8', '9', '12'],
    correctIndex: 2,
    explanation: '3² = 3 × 3 = 9. "Squared" means multiplying a number by itself.',
    tags: ['exponents', 'multiplication'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'math_medium_012',
    subject: 'math',
    difficulty: 'medium',
    question: 'Arrange in order from smallest: 0.75, 1/2, 0.3, 3/4',
    answers: ['0.3, 1/2, 0.75, 3/4', '0.3, 1/2, 3/4, 0.75', '1/2, 0.3, 0.75, 3/4', '0.75, 3/4, 1/2, 0.3'],
    correctIndex: 0,
    explanation: '0.3 = 0.30, 1/2 = 0.50, 0.75 = 0.75, 3/4 = 0.75. Order: 0.3, 1/2, 0.75, 3/4.',
    tags: ['fractions', 'decimals', 'ordering'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'math_medium_013',
    subject: 'math',
    difficulty: 'medium',
    question: 'What is 15% of 200?',
    answers: ['20', '25', '30', '35'],
    correctIndex: 2,
    explanation: '15% of 200 = 0.15 × 200 = 30. Or: 10% = 20, 5% = 10, so 15% = 30.',
    tags: ['percentages'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'math_medium_014',
    subject: 'math',
    difficulty: 'medium',
    question: 'What is 4.7 + 3.8?',
    answers: ['7.5', '8.2', '8.5', '9.1'],
    correctIndex: 2,
    explanation: '4.7 + 3.8 = 8.5. Align the decimal points and add: 7 + 8 = 15 (write 5, carry 1), 4 + 3 + 1 = 8.',
    tags: ['decimals', 'addition'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'math_medium_015',
    subject: 'math',
    difficulty: 'medium',
    question: 'If 2n = 18, what is n?',
    answers: ['7', '8', '9', '10'],
    correctIndex: 2,
    explanation: '2n = 18 means 2 × n = 18. Divide both sides by 2: n = 9.',
    tags: ['algebra'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'math_medium_016',
    subject: 'math',
    difficulty: 'medium',
    question: 'What is 56 ÷ 7?',
    answers: ['6', '7', '8', '9'],
    correctIndex: 2,
    explanation: '56 ÷ 7 = 8. Because 7 × 8 = 56.',
    tags: ['division'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'math_medium_017',
    subject: 'math',
    difficulty: 'medium',
    question: 'A bag has 5 red, 3 blue, and 2 green balls. What fraction are red?',
    answers: ['1/2', '5/10', '1/3', '3/10'],
    correctIndex: 1,
    explanation: '5 red out of 10 total = 5/10 = 1/2. Fractions represent parts of a whole.',
    tags: ['fractions', 'word problems'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'math_medium_018',
    subject: 'math',
    difficulty: 'medium',
    question: 'What is the next prime number after 11?',
    answers: ['12', '13', '14', '15'],
    correctIndex: 1,
    explanation: '13 is prime. A prime number has exactly 2 factors: 1 and itself. 12 = 2×6, 14 = 2×7, 15 = 3×5, but 13 has no other factors.',
    tags: ['number properties', 'primes'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'math_medium_019',
    subject: 'math',
    difficulty: 'medium',
    question: 'What is 1000 - 378?',
    answers: ['612', '622', '632', '642'],
    correctIndex: 1,
    explanation: '1000 - 378 = 622. Use the strategy: 378 + 622 = 1000.',
    tags: ['subtraction'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'math_medium_020',
    subject: 'math',
    difficulty: 'medium',
    question: 'A recipe needs 2.5 cups of flour. To make 3 batches, how much flour is needed?',
    answers: ['5.5 cups', '6 cups', '7 cups', '7.5 cups'],
    correctIndex: 3,
    explanation: '2.5 × 3 = 7.5 cups. Multiply the amount per batch by the number of batches.',
    tags: ['decimals', 'multiplication', 'word problems'],
    xpReward: 20,
    timeLimit: 25,
  },

  // ─── HARD ────────────────────────────────────────────────────────────────────
  {
    id: 'math_hard_001',
    subject: 'math',
    difficulty: 'hard',
    question: 'What is 15% of 340?',
    answers: ['44', '48', '51', '54'],
    correctIndex: 2,
    explanation: '15% of 340 = 0.15 × 340 = 51. Or: 10% = 34, 5% = 17, so 15% = 34 + 17 = 51.',
    tags: ['percentages'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'math_hard_002',
    subject: 'math',
    difficulty: 'hard',
    question: 'Simplify: (3 + 5) × 2 - 4 ÷ 2',
    answers: ['12', '14', '16', '18'],
    correctIndex: 1,
    explanation: 'Follow BODMAS/PEMDAS: brackets first (3+5)=8, then 8×2=16, then 4÷2=2, then 16-2=14.',
    hint: 'Remember: brackets, then multiply/divide, then add/subtract.',
    tags: ['order of operations'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'math_hard_003',
    subject: 'math',
    difficulty: 'hard',
    question: 'If 3x - 6 = 15, what is x?',
    answers: ['5', '6', '7', '8'],
    correctIndex: 2,
    explanation: '3x - 6 = 15 → 3x = 21 → x = 7. Add 6 to both sides, then divide by 3.',
    tags: ['algebra'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'math_hard_004',
    subject: 'math',
    difficulty: 'hard',
    question: 'What is the ratio of 3:5 written as a percentage (3 out of 8 total)?',
    answers: ['30%', '37.5%', '40%', '60%'],
    correctIndex: 1,
    explanation: '3 out of 8 = 3/8 = 0.375 = 37.5%. Divide the part by the whole and multiply by 100.',
    tags: ['ratios', 'percentages'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'math_hard_005',
    subject: 'math',
    difficulty: 'hard',
    question: 'What is the area of a triangle with base 10 cm and height 6 cm?',
    answers: ['25 cm²', '30 cm²', '45 cm²', '60 cm²'],
    correctIndex: 1,
    explanation: 'Area of triangle = ½ × base × height = ½ × 10 × 6 = 30 cm².',
    hint: 'Area of triangle = base × height ÷ 2.',
    tags: ['geometry', 'area'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'math_hard_006',
    subject: 'math',
    difficulty: 'hard',
    question: 'A car costs $12,000. It loses 20% of its value each year. What is it worth after 1 year?',
    answers: ['$9,000', '$9,600', '$10,000', '$10,400'],
    correctIndex: 1,
    explanation: '20% of $12,000 = $2,400. $12,000 - $2,400 = $9,600.',
    tags: ['percentages', 'word problems'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'math_hard_007',
    subject: 'math',
    difficulty: 'hard',
    question: 'What is the LCM (Lowest Common Multiple) of 4 and 6?',
    answers: ['8', '10', '12', '24'],
    correctIndex: 2,
    explanation: 'LCM of 4 and 6 is 12. Multiples of 4: 4, 8, 12... Multiples of 6: 6, 12... The smallest shared multiple is 12.',
    tags: ['number properties', 'multiples'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'math_hard_008',
    subject: 'math',
    difficulty: 'hard',
    question: 'Evaluate: 2³ + 4²',
    answers: ['20', '22', '24', '26'],
    correctIndex: 2,
    explanation: '2³ = 8 and 4² = 16. So 8 + 16 = 24.',
    tags: ['exponents'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'math_hard_009',
    subject: 'math',
    difficulty: 'hard',
    question: 'What is 5/8 expressed as a decimal?',
    answers: ['0.525', '0.6', '0.625', '0.65'],
    correctIndex: 2,
    explanation: '5 ÷ 8 = 0.625. Divide the numerator by the denominator.',
    tags: ['fractions', 'decimals'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'math_hard_010',
    subject: 'math',
    difficulty: 'hard',
    question: 'A shop offers 30% off a $45 item. How much do you pay?',
    answers: ['$28.50', '$30.00', '$31.50', '$33.00'],
    correctIndex: 2,
    explanation: '30% of $45 = $13.50. $45 - $13.50 = $31.50.',
    tags: ['percentages', 'word problems'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'math_hard_011',
    subject: 'math',
    difficulty: 'hard',
    question: 'If x/4 = 7, what is x?',
    answers: ['11', '21', '28', '35'],
    correctIndex: 2,
    explanation: 'x/4 = 7 means x ÷ 4 = 7. Multiply both sides by 4: x = 28.',
    tags: ['algebra'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'math_hard_012',
    subject: 'math',
    difficulty: 'hard',
    question: 'What is the perimeter of a right triangle with legs 3 cm and 4 cm?',
    answers: ['10 cm', '12 cm', '14 cm', '16 cm'],
    correctIndex: 1,
    explanation: 'Using Pythagoras: hypotenuse = √(3² + 4²) = √(9+16) = √25 = 5. Perimeter = 3 + 4 + 5 = 12 cm.',
    tags: ['geometry', 'Pythagoras'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'math_hard_013',
    subject: 'math',
    difficulty: 'hard',
    question: 'The ratio of boys to girls in a class is 3:2. If there are 30 students, how many are girls?',
    answers: ['10', '12', '14', '18'],
    correctIndex: 1,
    explanation: 'Total parts = 3+2 = 5. Girls = 2/5 of 30 = 12.',
    tags: ['ratios', 'word problems'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'math_hard_014',
    subject: 'math',
    difficulty: 'hard',
    question: 'What is 12 × 15?',
    answers: ['160', '170', '180', '190'],
    correctIndex: 2,
    explanation: '12 × 15 = 180. You can calculate: 12 × 10 = 120 and 12 × 5 = 60, then 120 + 60 = 180.',
    tags: ['multiplication'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'math_hard_015',
    subject: 'math',
    difficulty: 'hard',
    question: 'Simplify: 24/36',
    answers: ['1/2', '2/3', '3/4', '4/6'],
    correctIndex: 1,
    explanation: '24/36: divide both by their GCF (12). 24÷12 = 2, 36÷12 = 3. So 2/3.',
    tags: ['fractions', 'simplification'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'math_hard_016',
    subject: 'math',
    difficulty: 'hard',
    question: 'If a rectangle has a perimeter of 36 cm and a width of 8 cm, what is its length?',
    answers: ['8 cm', '10 cm', '12 cm', '14 cm'],
    correctIndex: 1,
    explanation: 'Perimeter = 2(l + w). 36 = 2(l + 8) → 18 = l + 8 → l = 10 cm.',
    tags: ['geometry', 'algebra', 'perimeter'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'math_hard_017',
    subject: 'math',
    difficulty: 'hard',
    question: 'What is the mean (average) of: 12, 18, 24, 6?',
    answers: ['12', '14', '15', '16'],
    correctIndex: 2,
    explanation: 'Mean = sum ÷ count. (12 + 18 + 24 + 6) ÷ 4 = 60 ÷ 4 = 15.',
    tags: ['statistics', 'mean'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'math_hard_018',
    subject: 'math',
    difficulty: 'hard',
    question: 'What is the circumference of a circle with radius 7 cm? (Use π ≈ 3.14)',
    answers: ['21.98 cm', '43.96 cm', '49 cm', '153.86 cm'],
    correctIndex: 1,
    explanation: 'Circumference = 2πr = 2 × 3.14 × 7 = 43.96 cm.',
    hint: 'Circumference = 2 × π × radius.',
    tags: ['geometry', 'circles'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'math_hard_019',
    subject: 'math',
    difficulty: 'hard',
    question: 'Which of these is NOT a factor of 60?',
    answers: ['12', '15', '18', '20'],
    correctIndex: 2,
    explanation: '18 is not a factor of 60. 60 ÷ 18 = 3.33... (not a whole number). 60 ÷ 12 = 5, 60 ÷ 15 = 4, 60 ÷ 20 = 3.',
    tags: ['factors', 'number properties'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'math_hard_020',
    subject: 'math',
    difficulty: 'hard',
    question: 'A shop sells pencils at 3 for $1. How many can you buy with $7?',
    answers: ['18', '20', '21', '24'],
    correctIndex: 2,
    explanation: '3 pencils per $1, so $7 buys 7 × 3 = 21 pencils.',
    tags: ['ratios', 'word problems'],
    xpReward: 35,
    timeLimit: 20,
  },
]
