import type { Question } from '../types'

export const SCIENCE_QUESTIONS: Question[] = [
  // ─── EASY ───────────────────────────────────────────────────────────────────
  {
    id: 'science_easy_001',
    subject: 'science',
    difficulty: 'easy',
    question: 'What do plants need from the sun to make their food?',
    answers: ['Water', 'Light', 'Soil', 'Wind'],
    correctIndex: 1,
    explanation: 'Plants use sunlight to make food through a process called photosynthesis. They also need water and carbon dioxide.',
    hint: 'Plants need this to grow — the sun provides it.',
    tags: ['plants', 'photosynthesis'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'science_easy_002',
    subject: 'science',
    difficulty: 'easy',
    question: 'How many legs does a spider have?',
    answers: ['4', '6', '8', '10'],
    correctIndex: 2,
    explanation: 'Spiders have 8 legs. This is why spiders are called arachnids, not insects. Insects only have 6 legs.',
    tags: ['animals', 'insects'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'science_easy_003',
    subject: 'science',
    difficulty: 'easy',
    question: 'What type of weather brings thunder and lightning?',
    answers: ['Blizzard', 'Fog', 'Thunderstorm', 'Heatwave'],
    correctIndex: 2,
    explanation: 'A thunderstorm brings thunder and lightning. Lightning is a huge spark of electricity in the sky, and thunder is the sound it makes.',
    tags: ['weather'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'science_easy_004',
    subject: 'science',
    difficulty: 'easy',
    question: 'What organ pumps blood around your body?',
    answers: ['Lungs', 'Brain', 'Heart', 'Stomach'],
    correctIndex: 2,
    explanation: 'The heart pumps blood through your body. It beats about 100,000 times a day, delivering oxygen and nutrients to every cell.',
    tags: ['human body'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'science_easy_005',
    subject: 'science',
    difficulty: 'easy',
    question: 'Which of these is an example of a push force?',
    answers: ['A magnet pulling a nail', 'Kicking a ball', 'Earth pulling rain down', 'A vacuum sucking up dust'],
    correctIndex: 1,
    explanation: 'Kicking a ball is a push force — your foot pushes the ball away. A push moves something away from you.',
    tags: ['forces', 'physics'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'science_easy_006',
    subject: 'science',
    difficulty: 'easy',
    question: 'What do caterpillars turn into?',
    answers: ['Moths only', 'Dragonflies', 'Butterflies or moths', 'Beetles'],
    correctIndex: 2,
    explanation: 'Caterpillars are the larval stage of butterflies and moths. They undergo metamorphosis inside a cocoon (moth) or chrysalis (butterfly).',
    tags: ['animals', 'life cycles'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'science_easy_007',
    subject: 'science',
    difficulty: 'easy',
    question: 'Which gas do humans breathe in to survive?',
    answers: ['Carbon dioxide', 'Nitrogen', 'Oxygen', 'Helium'],
    correctIndex: 2,
    explanation: 'We breathe in oxygen. Our cells use oxygen to release energy from food. We breathe out carbon dioxide as a waste product.',
    tags: ['human body', 'gases'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'science_easy_008',
    subject: 'science',
    difficulty: 'easy',
    question: 'What is the closest star to Earth?',
    answers: ['Sirius', 'The Moon', 'The Sun', 'Polaris'],
    correctIndex: 2,
    explanation: 'The Sun is the closest star to Earth — it is about 150 million km away. Without its light and heat, life on Earth would not be possible.',
    hint: 'We see it every day (when there are no clouds).',
    tags: ['space', 'stars'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'science_easy_009',
    subject: 'science',
    difficulty: 'easy',
    question: 'What do roots do for a plant?',
    answers: ['Make food using sunlight', 'Absorb water and nutrients from soil', 'Catch insects', 'Produce seeds'],
    correctIndex: 1,
    explanation: 'Roots anchor the plant in the soil and absorb water and minerals. These travel up through the stem to the leaves.',
    tags: ['plants'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'science_easy_010',
    subject: 'science',
    difficulty: 'easy',
    question: 'Which animal is a mammal?',
    answers: ['Salmon', 'Eagle', 'Dolphin', 'Frog'],
    correctIndex: 2,
    explanation: 'Dolphins are mammals. Mammals are warm-blooded, breathe air, give birth to live young, and feed their babies milk.',
    tags: ['animals', 'classification'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'science_easy_011',
    subject: 'science',
    difficulty: 'easy',
    question: 'What causes day and night on Earth?',
    answers: ['The Moon moving', 'Earth spinning on its axis', 'The Sun moving', 'Clouds blocking the Sun'],
    correctIndex: 1,
    explanation: 'Earth spins on its axis once every 24 hours. The side facing the Sun has day, and the side facing away has night.',
    tags: ['earth science', 'space'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'science_easy_012',
    subject: 'science',
    difficulty: 'easy',
    question: 'Ice is water in which state?',
    answers: ['Gas', 'Liquid', 'Solid', 'Plasma'],
    correctIndex: 2,
    explanation: 'Ice is solid water. When water freezes below 0°C (32°F), it becomes solid ice.',
    tags: ['states of matter'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'science_easy_013',
    subject: 'science',
    difficulty: 'easy',
    question: 'What do bees collect from flowers to make honey?',
    answers: ['Pollen and nectar', 'Dew and sap', 'Seeds and pollen', 'Nectar only'],
    correctIndex: 0,
    explanation: 'Bees collect nectar (a sweet liquid) to make honey and pollen (a protein source) to feed their larvae.',
    tags: ['animals', 'plants'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'science_easy_014',
    subject: 'science',
    difficulty: 'easy',
    question: 'Which part of the body controls everything you do and think?',
    answers: ['Heart', 'Lungs', 'Brain', 'Stomach'],
    correctIndex: 2,
    explanation: 'The brain is the control center of the body. It processes information, controls movement, stores memories, and keeps your body working.',
    tags: ['human body'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'science_easy_015',
    subject: 'science',
    difficulty: 'easy',
    question: 'What are clouds made of?',
    answers: ['Cotton', 'Smoke', 'Tiny water droplets or ice crystals', 'Gas bubbles'],
    correctIndex: 2,
    explanation: 'Clouds are made of tiny water droplets or ice crystals floating in the air. They form when warm moist air cools and water condenses.',
    tags: ['weather', 'water cycle'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'science_easy_016',
    subject: 'science',
    difficulty: 'easy',
    question: 'Which of these is NOT a living thing?',
    answers: ['Mushroom', 'Rock', 'Tree', 'Bacteria'],
    correctIndex: 1,
    explanation: 'A rock is not alive. Living things grow, reproduce, respond to their environment, and need energy. Rocks do none of these.',
    tags: ['life science', 'classification'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'science_easy_017',
    subject: 'science',
    difficulty: 'easy',
    question: 'What is the name of the force that pulls objects towards the ground?',
    answers: ['Magnetism', 'Friction', 'Gravity', 'Tension'],
    correctIndex: 2,
    explanation: 'Gravity is the force that pulls objects toward Earth. It keeps us on the ground and makes dropped things fall.',
    tags: ['forces', 'physics'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'science_easy_018',
    subject: 'science',
    difficulty: 'easy',
    question: 'What do herbivores eat?',
    answers: ['Only meat', 'Plants and animals', 'Only plants', 'Only insects'],
    correctIndex: 2,
    explanation: 'Herbivores only eat plants. Examples include cows, rabbits, and elephants. "Herbi" comes from Latin meaning plant.',
    tags: ['animals', 'food chains'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'science_easy_019',
    subject: 'science',
    difficulty: 'easy',
    question: 'Which planet do we live on?',
    answers: ['Mars', 'Venus', 'Earth', 'Jupiter'],
    correctIndex: 2,
    explanation: 'We live on Earth, the third planet from the Sun. Earth is the only known planet with liquid water on its surface and life.',
    tags: ['space', 'planets'],
    xpReward: 10,
    timeLimit: 30,
  },
  {
    id: 'science_easy_020',
    subject: 'science',
    difficulty: 'easy',
    question: 'What does a thermometer measure?',
    answers: ['Wind speed', 'Rainfall', 'Temperature', 'Air pressure'],
    correctIndex: 2,
    explanation: 'A thermometer measures temperature — how hot or cold something is. It works because liquids expand when heated.',
    tags: ['measurement', 'weather'],
    xpReward: 10,
    timeLimit: 30,
  },

  // ─── MEDIUM ─────────────────────────────────────────────────────────────────
  {
    id: 'science_medium_001',
    subject: 'science',
    difficulty: 'medium',
    question: 'What is the process by which water turns from liquid into vapor called?',
    answers: ['Condensation', 'Precipitation', 'Evaporation', 'Transpiration'],
    correctIndex: 2,
    explanation: 'Evaporation is when liquid water heats up and turns into water vapor (gas). It is a key part of the water cycle.',
    tags: ['water cycle', 'states of matter'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'science_medium_002',
    subject: 'science',
    difficulty: 'medium',
    question: 'In a food chain, what is an organism called that makes its own food?',
    answers: ['Consumer', 'Decomposer', 'Producer', 'Predator'],
    correctIndex: 2,
    explanation: 'Producers (like plants) make their own food using sunlight through photosynthesis. They form the base of every food chain.',
    tags: ['food chains', 'ecosystems'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'science_medium_003',
    subject: 'science',
    difficulty: 'medium',
    question: 'How long does Earth take to orbit the Sun?',
    answers: ['24 hours', '28 days', '365 days', '10 years'],
    correctIndex: 2,
    explanation: 'Earth takes about 365 days (one year) to orbit the Sun. This is why we have a year with 365 days (and a leap year with 366 every 4 years).',
    tags: ['space', 'solar system'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'science_medium_004',
    subject: 'science',
    difficulty: 'medium',
    question: 'Which state of matter has a fixed volume but no fixed shape?',
    answers: ['Solid', 'Liquid', 'Gas', 'Plasma'],
    correctIndex: 1,
    explanation: 'Liquids have a fixed volume (amount) but take the shape of their container. Solids keep their shape; gases fill all available space.',
    tags: ['states of matter'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'science_medium_005',
    subject: 'science',
    difficulty: 'medium',
    question: 'What is the largest planet in our solar system?',
    answers: ['Saturn', 'Neptune', 'Jupiter', 'Uranus'],
    correctIndex: 2,
    explanation: 'Jupiter is the largest planet — so large that all other planets could fit inside it. It is a gas giant with a famous Great Red Spot storm.',
    tags: ['space', 'solar system'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'science_medium_006',
    subject: 'science',
    difficulty: 'medium',
    question: 'What is the chemical symbol for water?',
    answers: ['WO', 'HO', 'H₂O', 'H₂O₂'],
    correctIndex: 2,
    explanation: 'Water is H₂O — two hydrogen atoms bonded to one oxygen atom. The subscript 2 means there are 2 hydrogen atoms.',
    tags: ['chemistry'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'science_medium_007',
    subject: 'science',
    difficulty: 'medium',
    question: 'What type of energy does the Sun produce that we use in solar panels?',
    answers: ['Chemical energy', 'Sound energy', 'Nuclear energy', 'Electromagnetic (light) energy'],
    correctIndex: 3,
    explanation: 'Solar panels capture electromagnetic energy (light and heat) from the Sun and convert it into electricity.',
    tags: ['energy', 'physics'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'science_medium_008',
    subject: 'science',
    difficulty: 'medium',
    question: 'What role do decomposers play in an ecosystem?',
    answers: ['They hunt prey', 'They break down dead organisms', 'They produce food from sunlight', 'They pollinate flowers'],
    correctIndex: 1,
    explanation: 'Decomposers like fungi and bacteria break down dead plants and animals, returning nutrients to the soil for plants to use again.',
    tags: ['ecosystems', 'food chains'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'science_medium_009',
    subject: 'science',
    difficulty: 'medium',
    question: 'Which gas do plants absorb from the air during photosynthesis?',
    answers: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Argon'],
    correctIndex: 2,
    explanation: 'Plants absorb carbon dioxide (CO₂) from the air. Using sunlight and water, they convert CO₂ into glucose (food) and release oxygen.',
    tags: ['plants', 'photosynthesis'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'science_medium_010',
    subject: 'science',
    difficulty: 'medium',
    question: 'What is the Moon\'s effect on Earth\'s oceans called?',
    answers: ['Gravity waves', 'Tides', 'Currents', 'Tsunamis'],
    correctIndex: 1,
    explanation: 'The Moon\'s gravity pulls on Earth\'s oceans, causing tides. High tide occurs when ocean water is pulled toward the Moon; low tide is when it is pulled away.',
    tags: ['space', 'earth science'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'science_medium_011',
    subject: 'science',
    difficulty: 'medium',
    question: 'What are the three primary colors of light?',
    answers: ['Red, yellow, blue', 'Red, green, blue', 'Cyan, magenta, yellow', 'Orange, green, violet'],
    correctIndex: 1,
    explanation: 'The primary colors of light are red, green, and blue (RGB). Combining all three in equal amounts makes white light.',
    tags: ['light', 'physics'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'science_medium_012',
    subject: 'science',
    difficulty: 'medium',
    question: 'What is the process when a solid turns directly into a gas called?',
    answers: ['Evaporation', 'Melting', 'Sublimation', 'Condensation'],
    correctIndex: 2,
    explanation: 'Sublimation is when a solid turns directly into a gas without becoming liquid first. Dry ice (frozen CO₂) is a common example.',
    tags: ['states of matter', 'chemistry'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'science_medium_013',
    subject: 'science',
    difficulty: 'medium',
    question: 'Which layer of Earth is liquid and surrounds the solid inner core?',
    answers: ['Crust', 'Mantle', 'Outer core', 'Inner core'],
    correctIndex: 2,
    explanation: 'The outer core is liquid iron and nickel surrounding the solid inner core. The flowing liquid creates Earth\'s magnetic field.',
    tags: ['earth science'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'science_medium_014',
    subject: 'science',
    difficulty: 'medium',
    question: 'What is the unit of force in science?',
    answers: ['Watt', 'Joule', 'Newton', 'Kilogram'],
    correctIndex: 2,
    explanation: 'Force is measured in Newtons (N), named after Sir Isaac Newton who described the laws of motion.',
    tags: ['forces', 'measurement'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'science_medium_015',
    subject: 'science',
    difficulty: 'medium',
    question: 'An ecosystem where few plants grow due to low rainfall is called a:',
    answers: ['Rainforest', 'Desert', 'Tundra', 'Wetland'],
    correctIndex: 1,
    explanation: 'A desert receives very little rainfall (less than 250 mm per year). Plants and animals there have special adaptations to survive with little water.',
    tags: ['ecosystems', 'biomes'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'science_medium_016',
    subject: 'science',
    difficulty: 'medium',
    question: 'What is the speed of light approximately equal to?',
    answers: ['300 km/s', '3,000 km/s', '300,000 km/s', '3,000,000 km/s'],
    correctIndex: 2,
    explanation: 'Light travels at approximately 300,000 km per second. Light from the Sun takes about 8 minutes to reach Earth.',
    tags: ['physics', 'light'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'science_medium_017',
    subject: 'science',
    difficulty: 'medium',
    question: 'What is the hardest natural substance on Earth?',
    answers: ['Iron', 'Quartz', 'Diamond', 'Granite'],
    correctIndex: 2,
    explanation: 'Diamond is the hardest natural substance. It scores 10 on the Mohs hardness scale. Diamonds are a form of carbon.',
    tags: ['earth science', 'chemistry'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'science_medium_018',
    subject: 'science',
    difficulty: 'medium',
    question: 'What causes a rainbow to appear?',
    answers: ['Water reflecting moonlight', 'Sunlight passing through raindrops and splitting into colors', 'Pollution in the atmosphere', 'Ice crystals in clouds'],
    correctIndex: 1,
    explanation: 'Rainbows form when sunlight enters water droplets in the air, slows down, and splits into its spectrum of colors (red, orange, yellow, green, blue, indigo, violet).',
    tags: ['light', 'weather', 'physics'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'science_medium_019',
    subject: 'science',
    difficulty: 'medium',
    question: 'What is the function of red blood cells?',
    answers: ['Fight infection', 'Carry oxygen around the body', 'Help blood clot', 'Produce hormones'],
    correctIndex: 1,
    explanation: 'Red blood cells carry oxygen from the lungs to all parts of the body, using a protein called hemoglobin that gives blood its red color.',
    tags: ['human body'],
    xpReward: 20,
    timeLimit: 25,
  },
  {
    id: 'science_medium_020',
    subject: 'science',
    difficulty: 'medium',
    question: 'What type of rock forms from cooled lava or magma?',
    answers: ['Sedimentary', 'Metamorphic', 'Igneous', 'Limestone'],
    correctIndex: 2,
    explanation: 'Igneous rock forms when molten rock (lava above ground, magma below) cools and solidifies. Granite and basalt are common igneous rocks.',
    tags: ['earth science', 'rocks'],
    xpReward: 20,
    timeLimit: 25,
  },

  // ─── HARD ────────────────────────────────────────────────────────────────────
  {
    id: 'science_hard_001',
    subject: 'science',
    difficulty: 'hard',
    question: 'What is the powerhouse of the cell?',
    answers: ['Nucleus', 'Ribosome', 'Mitochondria', 'Vacuole'],
    correctIndex: 2,
    explanation: 'Mitochondria produce ATP (adenosine triphosphate), the energy currency of the cell. They have their own DNA and originated as separate bacteria long ago.',
    tags: ['cell biology'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'science_hard_002',
    subject: 'science',
    difficulty: 'hard',
    question: 'What is Newton\'s Second Law of Motion?',
    answers: ['Every action has an equal and opposite reaction', 'Force equals mass times acceleration', 'An object at rest stays at rest unless acted upon', 'Objects in motion accelerate towards Earth'],
    correctIndex: 1,
    explanation: 'Newton\'s Second Law states F = ma. Force equals mass multiplied by acceleration. A heavier object needs more force to accelerate.',
    tags: ['physics', 'forces'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'science_hard_003',
    subject: 'science',
    difficulty: 'hard',
    question: 'What is the pH level of a neutral substance?',
    answers: ['0', '5', '7', '14'],
    correctIndex: 2,
    explanation: 'A neutral substance has a pH of 7 (like pure water). Acids are below 7, and bases (alkalis) are above 7. The pH scale runs from 0 to 14.',
    tags: ['chemistry', 'acids and bases'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'science_hard_004',
    subject: 'science',
    difficulty: 'hard',
    question: 'Which organelle controls what enters and leaves a cell?',
    answers: ['Cell wall', 'Nucleus', 'Cell membrane', 'Cytoplasm'],
    correctIndex: 2,
    explanation: 'The cell membrane (plasma membrane) is a selectively permeable barrier controlling what substances enter and leave the cell.',
    tags: ['cell biology'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'science_hard_005',
    subject: 'science',
    difficulty: 'hard',
    question: 'What is the process by which plants release water vapor through their leaves?',
    answers: ['Photosynthesis', 'Respiration', 'Transpiration', 'Osmosis'],
    correctIndex: 2,
    explanation: 'Transpiration is the evaporation of water from plant leaves through tiny pores called stomata. It helps draw water up from the roots.',
    tags: ['plants', 'water cycle'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'science_hard_006',
    subject: 'science',
    difficulty: 'hard',
    question: 'What is the chemical formula for table salt?',
    answers: ['KCl', 'NaOH', 'NaCl', 'CaCl₂'],
    correctIndex: 2,
    explanation: 'Table salt is sodium chloride, NaCl — one sodium (Na) atom bonded to one chlorine (Cl) atom. It forms when an acid and base react.',
    tags: ['chemistry'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'science_hard_007',
    subject: 'science',
    difficulty: 'hard',
    question: 'What type of bond forms between a sodium and chlorine atom?',
    answers: ['Covalent bond', 'Ionic bond', 'Hydrogen bond', 'Metallic bond'],
    correctIndex: 1,
    explanation: 'Sodium and chlorine form an ionic bond. Sodium loses an electron (becoming Na⁺) and chlorine gains it (becoming Cl⁻). Opposite charges attract.',
    tags: ['chemistry', 'atomic structure'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'science_hard_008',
    subject: 'science',
    difficulty: 'hard',
    question: 'What is the variable that a scientist deliberately changes in an experiment?',
    answers: ['Dependent variable', 'Control variable', 'Independent variable', 'Constant'],
    correctIndex: 2,
    explanation: 'The independent variable is what the scientist deliberately changes. The dependent variable is what is measured as a result.',
    tags: ['scientific method'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'science_hard_009',
    subject: 'science',
    difficulty: 'hard',
    question: 'What is the term for the bending of light as it passes from one medium to another?',
    answers: ['Reflection', 'Diffraction', 'Refraction', 'Dispersion'],
    correctIndex: 2,
    explanation: 'Refraction is the bending of light when it moves from one material to another (like air to water). This is why a straw looks bent in a glass of water.',
    tags: ['physics', 'light'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'science_hard_010',
    subject: 'science',
    difficulty: 'hard',
    question: 'Which part of a plant cell is NOT found in an animal cell?',
    answers: ['Mitochondria', 'Cell wall', 'Nucleus', 'Cell membrane'],
    correctIndex: 1,
    explanation: 'Plant cells have a rigid cell wall (made of cellulose) that surrounds the cell membrane. Animal cells do not have a cell wall.',
    tags: ['cell biology'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'science_hard_011',
    subject: 'science',
    difficulty: 'hard',
    question: 'What is the name of the layer of the atmosphere that protects us from harmful UV rays?',
    answers: ['Troposphere', 'Stratosphere (ozone layer)', 'Mesosphere', 'Thermosphere'],
    correctIndex: 1,
    explanation: 'The ozone layer is found in the stratosphere. Ozone (O₃) absorbs most of the Sun\'s harmful ultraviolet radiation before it reaches Earth\'s surface.',
    tags: ['earth science', 'atmosphere'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'science_hard_012',
    subject: 'science',
    difficulty: 'hard',
    question: 'What is the process called when DNA copies itself before cell division?',
    answers: ['Transcription', 'Translation', 'Replication', 'Mutation'],
    correctIndex: 2,
    explanation: 'DNA replication is when a cell makes an exact copy of its DNA before dividing. Each new cell gets a complete set of genetic instructions.',
    tags: ['cell biology', 'genetics'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'science_hard_013',
    subject: 'science',
    difficulty: 'hard',
    question: 'In physics, what is the unit of electrical resistance?',
    answers: ['Volt', 'Ampere', 'Watt', 'Ohm'],
    correctIndex: 3,
    explanation: 'Electrical resistance is measured in Ohms (Ω), named after Georg Simon Ohm. Ohm\'s Law states V = IR (Voltage = Current × Resistance).',
    tags: ['physics', 'electricity'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'science_hard_014',
    subject: 'science',
    difficulty: 'hard',
    question: 'What is the term for the minimum energy needed to start a chemical reaction?',
    answers: ['Kinetic energy', 'Activation energy', 'Potential energy', 'Thermal energy'],
    correctIndex: 1,
    explanation: 'Activation energy is the minimum energy required to start a chemical reaction. Catalysts work by lowering the activation energy needed.',
    tags: ['chemistry', 'reactions'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'science_hard_015',
    subject: 'science',
    difficulty: 'hard',
    question: 'What is the Richter scale used to measure?',
    answers: ['Wind speed', 'Ocean depth', 'Earthquake magnitude', 'Volcanic temperature'],
    correctIndex: 2,
    explanation: 'The Richter scale measures the magnitude (energy released) of earthquakes. It is a logarithmic scale — each step up represents 10× more energy.',
    tags: ['earth science'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'science_hard_016',
    subject: 'science',
    difficulty: 'hard',
    question: 'Which type of electromagnetic radiation has the highest frequency?',
    answers: ['Radio waves', 'Visible light', 'X-rays', 'Gamma rays'],
    correctIndex: 3,
    explanation: 'Gamma rays have the highest frequency (and energy) in the electromagnetic spectrum. They are produced by radioactive decay and nuclear reactions.',
    tags: ['physics', 'electromagnetic spectrum'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'science_hard_017',
    subject: 'science',
    difficulty: 'hard',
    question: 'What happens to the pressure of a gas when its volume is reduced (temperature stays constant)?',
    answers: ['Pressure decreases', 'Pressure stays the same', 'Pressure increases', 'The gas turns to liquid'],
    correctIndex: 2,
    explanation: 'According to Boyle\'s Law, when volume decreases and temperature stays constant, pressure increases. Gas particles have less space and collide more often.',
    tags: ['physics', 'gas laws'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'science_hard_018',
    subject: 'science',
    difficulty: 'hard',
    question: 'What are tectonic plates?',
    answers: ['Layers of the atmosphere', 'Large pieces of Earth\'s crust that move', 'Types of volcanic rock', 'Ocean floor trenches'],
    correctIndex: 1,
    explanation: 'Tectonic plates are massive slabs of Earth\'s crust and upper mantle. They move very slowly (a few cm per year) and their collisions cause earthquakes, volcanoes, and mountains.',
    tags: ['earth science'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'science_hard_019',
    subject: 'science',
    difficulty: 'hard',
    question: 'What does the nucleus of an atom contain?',
    answers: ['Electrons and neutrons', 'Protons and electrons', 'Protons and neutrons', 'Electrons only'],
    correctIndex: 2,
    explanation: 'The nucleus contains protons (positive charge) and neutrons (no charge). Electrons orbit the nucleus in shells. The number of protons determines the element.',
    tags: ['chemistry', 'atomic structure'],
    xpReward: 35,
    timeLimit: 20,
  },
  {
    id: 'science_hard_020',
    subject: 'science',
    difficulty: 'hard',
    question: 'What is the main difference between mitosis and meiosis?',
    answers: ['Mitosis produces sex cells; meiosis produces body cells', 'Mitosis creates 4 cells; meiosis creates 2', 'Mitosis creates 2 identical cells; meiosis creates 4 genetically different cells', 'They are the same process'],
    correctIndex: 2,
    explanation: 'Mitosis produces 2 identical daughter cells for growth and repair. Meiosis produces 4 genetically unique cells (sperm or eggs) for sexual reproduction.',
    tags: ['cell biology', 'genetics'],
    xpReward: 35,
    timeLimit: 20,
  },
]
